- src/components/TableBrowser/TableBrowser.tsx
- src/components/Vizmapper/Forms/BypassForm.tsx
- src/components/Vizmapper/Forms/MappingForm/ContinuousMappingForm/index.tsx
- src/components/Vizmapper/Forms/MappingForm/DiscreteMappingForm.tsx
- src/components/Vizmapper/Forms/MappingForm/index.tsx
- src/components/Vizmapper/VisualPropertyRender/EdgeArrowShape.tsx
- src/components/Vizmapper/VisualPropertyRender/EdgeLine.tsx
- src/components/Vizmapper/VisualPropertyRender/NodeBorderLine.tsx
- src/components/Vizmapper/VisualPropertyRender/NodeShape.tsx
- src/components/Vizmapper/VisualPropertyRender/Visibility.tsx
- src/components/Vizmapper/index.tsx
- src/models/VisualStyleModel/impl/MappingFunctionImpl.ts
- src/models/VisualStyleModel/impl/VisualStyleImpl.ts
- src/store/TableStore.ts
- src/store/VisualStyleStore.ts
Replace all instances(that I could find so far) of type specific strings with their equivalent enums constants.
> use type enums instead of hard coded strings

- src/components/ToolBar/BaseMenuProps.ts
- src/components/ToolBar/DataMenu/LoadDemoNetworksMenuItem.tsx
- src/components/ToolBar/DataMenu/LoadFromNdexDialog.tsx
- src/components/ToolBar/DataMenu/LoadFromNdexMenuItem.tsx
- src/components/ToolBar/DataMenu/RemoveAllNetworksMenuItem.tsx
- src/components/ToolBar/DataMenu/RemoveNetworkMenuItem.tsx
- src/components/ToolBar/DataMenu/index.tsx
- src/components/ToolBar/DataMenu/menu-generator.tsx
- src/components/ToolBar/DataMenu/workspace-manager.ts
- src/components/ToolBar/EditMenu/index.ts
- src/components/Workspace/WorkspaceEditor.tsx
- src/store/NetworkStore.ts
- src/store/NetworkSummaryStore.ts
- src/store/TableStore.ts
- src/store/ViewModelStore.ts
- src/store/VisualStyleStore.ts
- src/store/WorkspaceStore.ts
- src/store/hooks/useWorkspaceManager.ts
- src/store/persist/db.ts
Some updates to the models (adding missing delete functions), and implemented command / menu items based on that.
New manager hook added to handle cascading events, like deletion from workspace.
> Menu cleanup

- README.md
CW-46 Create a documentation page for developers in Cy-web github repo
> CW-46 Create a documentation page for developers in Cy-web github repo 

- src/components/ToolBar/ToolBar.tsx
- src/components/Vizmapper/Forms/BypassForm.tsx
- src/components/Vizmapper/Forms/DefaultValueForm.tsx
- src/components/Vizmapper/Forms/MappingForm/index.tsx
- remove unimplemented toolbar drop down menus
- disable search bar and show a 'not implemented' tooltip
- remove tooltips for the vizmapper buttons since it interferred with scrolling properly
> Minor misc. changes to the ui for the prototype

- src/components/NetworkPanel/CyjsRenderer/CyjsRenderer.tsx
- src/components/NetworkPanel/CyjsRenderer/cyjs-util.ts
- src/components/TableBrowser/TableBrowser.tsx
- src/components/Vizmapper/Forms/BypassForm.tsx
- src/models/VisualStyleModel/VisualPropertyName.ts
- src/models/VisualStyleModel/impl/DefaultVisualStyle.ts
- src/models/VisualStyleModel/impl/cxVisualPropertyConverter.ts
- src/models/VisualStyleModel/impl/cyJsVisualPropertyConverter.ts
- src/store/ViewModelStore.ts
Selection is now a part of Visual Style and has a special handler in the Cyjs mapping generator. Mouseover event is also handled and add underlay to show which element is pointed by the mouse pointer.
> Selection bug

- src/components/Messages/SnackbarMessageList.tsx
- src/components/Messages/index.tsx
- src/components/ToolBar/DataMenu/CopyNetworkToNDExMenuItem.tsx
- src/components/ToolBar/DataMenu/LoadFromNdexDialog.tsx
- src/components/ToolBar/DataMenu/SaveToNDExMenuItem.tsx
- src/components/Workspace/WorkspaceEditor.tsx
- src/models/Message.ts
- src/store/useMessageStore.ts
- add message store that components can push messages to with a specified duration
- add a message list component that processes messages one at a time, once the message duration is finished, increment local state to display the next message
- ui changes requested by rudi re. NDEx import
> add a message indicator when users send a save/overwrite to ndex request

- src/components/Workspace/NetworkBrowserPanel/NetworkBrowserPanel.tsx
- src/store/NetworkStore.ts
- src/store/WorkspaceStore.ts
- src/store/hooks/useWorkspaceManager.ts
Deletion fails in the current branch, and this fixed it by filtering too many events fired by the store. Also, Visual Style will be set to target network correctly.
> Deletion bug

- package-lock.json
- package.json
- src/App.tsx
- src/AppConfigContext.ts
- src/assets/config.json
- src/components/SummaryPanel/NetworkPropertyPanel.tsx
- src/components/TableBrowser/TableBrowser.tsx
- src/components/TableBrowser/TableBrowserContextMenu.tsx
- src/models/TableModel/impl/InMemoryTable.ts
- unittest/model/InMemoryTableImpl.spec.ts
- add basename param to the react router browser to allow it to be deployed to a sub folder
- fix bug where the summary string would be undefined when stripping p tags from the rich text editor output
- fix bug where selected node data would not update properly when edited in the table browser
- fix bug where the table browser doesnt scroll up with table rows are filtered via selection
> Lab deploy bug fixes

- src/components/PopupPanel/PopupPanel.tsx
- src/components/Workspace/WorkspaceEditor.tsx
- src/features/HierarchyViewer/store/useHierarchyViewerManager.tsx
- src/models/UiModel/Ui.ts
- src/store/UiStateStore.ts
UI states will be updated based on the data type, and unnecessary popup will be removed. Also, side panel will be open/close based on the data type.
> CW-85 Popup will be disabled when hierarchy is not detected.

- src/components/TableBrowser/TableBrowser.tsx
> fix issue related to displaying the wrong number of nodes and edges

- src/store/io/exportCX.ts
fix more issues related to network attributes
> Network attribute fix

- src/store/TableStore.ts
Accidentally left out a fix related to renaming tables.
Most of the changes here are auto formatting related, here is the link to the actual change:
https://github.com/cytoscape/cytoscape-web/compare/development...network-attribute-fix?expand=1#diff-48898f82a2d395175baf800e5f75a0d4d704f900ef4aef60ef8335d62dca8e76R149
> additional fix for updating the table when the columns change

- src/components/AppShell.tsx
- src/components/ExternalLoading/ExternalNetworkLoadingPanel.tsx
- src/components/FloatingToolBar/ShareNetworkButtton.tsx
- src/components/LayoutTools/LayoutToolsBasePanel.tsx
- src/components/LayoutTools/LayoutToolsPanel.tsx
- src/components/LayoutTools/index.tsx
- src/components/SummaryPanel/NetworkPropertyPanel.tsx
- src/components/TableBrowser/TableBrowser.tsx
- src/components/Vizmapper/index.tsx
- src/components/Workspace/NetworkBrowserPanel/NetworkBrowserPanel.tsx
- src/components/Workspace/WorkspaceEditor.tsx
- src/features/HierarchyViewer/components/MainPanel.tsx
- src/models/UiModel/Panel.ts
- src/models/UiModel/Ui.ts
- src/store/UiStateStore.ts
Sharing function bugs resolved in this branch.
- Sharing button extracts base server name (including sub directory) correctly
- Both node & edge selection will be copied by the Share button
- Panel states will be encoded when using Share button
> Query params

- src/components/TableBrowser/TableBrowser.tsx
- src/utils/is-url.ts
- if a string value can be parsed to a url, display it in a uri cell so that users can click the link to open it in a new tab
- fix bug where a user would click a cell and the table browser would scroll to the top of the table
> misc table browser tweaks

- src/components/FloatingToolBar/ShareNetworkButtton.tsx
- src/components/SummaryPanel/NetworkPropertyPanel.tsx
- src/components/Workspace/WorkspaceEditor.tsx
When switching current network, URL and selection states were inconsistent. This fixes the problem.
Also, it fixed CW-111 (Table browser will have correct target network ID when switching network).
> Network switching issues

- src/components/AppShell.tsx
- src/components/NetworkPanel/CyjsRenderer/CyjsRenderer.tsx
- src/components/TableBrowser/NetworkInfoPanel.tsx
- src/components/TableBrowser/TableBrowser.tsx
- src/components/Vizmapper/VisualPropertyRender/Number.tsx
- src/components/Workspace/WorkspaceEditor.tsx
- src/models/UiModel/TableUi.ts
- src/models/UiModel/Ui.ts
- src/models/ViewModel/NetworkView.ts
- src/models/VisualStyleModel/VisualPropertyName.ts
- src/models/VisualStyleModel/impl/CyjsProperties/CyjsVisualPropertyName.ts
- src/models/VisualStyleModel/impl/DefaultVisualStyle.ts
- src/models/VisualStyleModel/impl/compute-view-util.ts
- src/models/VisualStyleModel/impl/cxVisualPropertyConverter.ts
- src/models/VisualStyleModel/impl/cyJsVisualPropertyConverter.ts
- src/store/UiStateStore.ts
- src/store/ViewModelStore.ts
- src/store/persist/db.ts
- persist ui state to indexeddb
- apply default heirarchical layout properly when hcx doesn't have one
- fix performance issues related to viewmodels and hoveredElement rendering the table browser on mouse move
- add z-order visual property support
- add network info tab in the table browser
> Persist UI state

- src/components/AppShell.tsx
- src/components/ExternalLoading/ExternalNetworkLoadingPanel.tsx
- src/components/SummaryPanel/NetworkPropertyPanel.tsx
- src/components/TableBrowser/NetworkInfoPanel.tsx
- src/components/UpdateNetworkDialog.tsx
- src/components/Workspace/WorkspaceEditor.tsx
- src/models/WorkspaceModel/Workspace.ts
- src/store/WorkspaceStore.ts
- src/store/hooks/useWorkspaceManager.ts
- src/utils/wait-seconds.ts
- when the user loads a network in the workspace in a url , let them know if there is a new version of it and prompt them to make a copy of their network and load the new version
> Update network dialog

- src/App.tsx
- src/RedirectPanel.tsx
All invalid routs will be redirected to the root of the application and it avoids the random crashes.
> Routing error handling (CW-129)

- src/App.tsx
- src/Error.tsx
Reset workspace button will be displayed when unknown error happens.
> Reset button

- src/Error.tsx
Dialog has been removed and wording updated.
> Confirmation dialog has been removed.

- src/components/AppShell.tsx
- src/store/persist/db.ts
- src/store/persist/migrations.ts
- adds `applyMigrations` function that applies migrations before the app is initialized
- each breaking model change should supply its own upgrade function, see commented example in migrations.ts
> Dexie migrations

- src/components/TableBrowser/TableBrowser.tsx
- reduce height of the table browser so that the scroll bar would not be cut off
> fix CW-130

- src/components/AppShell.tsx
- src/components/Workspace/WorkspaceEditor.tsx
- ui state loaded from db and then search params override ui state
- fixes issue where urls would not set ui state properly
> move url param loading logic to the appshell

- src/components/ToolBar/DataMenu/LoadFromNdexDialog.tsx
- rename the 'done' button to 'cancel'
- close the dialog after the user hits the confirm button
- show message saying the user loaded X networks after the click the confirm button
- fix performance issue where each key press in the form would rerender the whole dialog
> misc load from ndex dialog fixes/changes

- src/components/ToolBar/DataMenu/LoadFromNdexDialog.tsx
- src/features/LLMQuery/components/RunLLMQueryMenuItem.tsx
- press enter to initiate search in the load from ndex dialog
- show loading state when a user initiates search in the load from ndex dialog
- fix issue with gene names not being processed correctly
- show error message when the gene id query from ndex fails
> misc fixes

- src/components/AppShell.tsx
- src/components/NetworkPanel/CyjsRenderer/CyjsRenderer.tsx
- src/features/HierarchyViewer/store/ndexQueryFetcher.ts
- src/models/VisualStyleModel/impl/compute-view-util.ts
The cause of missing layouts, inconsistent members in the interaction network was corrupted cache. This fix retry the fetch and make sure View Model and network models have same members.
> Recovery code for inconsistent cache

- src/store/ViewModelStore.ts
- unittest/store/ViewModelStore.test.ts
Update functions for node / edge views have been added. Now you can add / delete those objects from the store.
> API update for View Model

- src/components/Vizmapper/Forms/VisualPropertyValueForm.tsx
> Fix CW-159

- src/components/ToolBar/DataMenu/UploadNetworkMenuItem.tsx
> Fix CW-165

- package-lock.json
- package.json
- src/features/HierarchyViewer/components/MainPanel.tsx
- src/features/HierarchyViewer/components/SubNetworkPanel.tsx
- src/features/HierarchyViewer/store/ndexQueryFetcher.ts
From this version, it forces to fetch the data and leave the caching to TanstackQuery.
> Lost layout

- src/components/Vizmapper/Forms/VisualPropertyValueForm.tsx
> Fix CW-174

- package-lock.json
- src/components/NetworkPanel/CyjsRenderer/CyjsRenderer.tsx
- src/components/NetworkPanel/CyjsRenderer/cyjs-util.ts
- src/components/NetworkPanel/NetworkTab.tsx
- src/components/NetworkPanel/NetworkTabs.tsx
- src/components/Workspace/SidePanel/SidePanel.tsx
- src/features/HierarchyViewer/components/FilterPanel/AttributeSelector.tsx
- src/features/HierarchyViewer/components/FilterPanel/CheckboxFilter.tsx
- src/features/HierarchyViewer/components/FilterPanel/CompatibleVisualMappings.ts
- src/features/HierarchyViewer/components/FilterPanel/FilterPanel.tsx
- src/features/HierarchyViewer/components/FilterPanel/ModeSelector.tsx
- src/features/HierarchyViewer/components/FilterPanel/index.ts
- src/features/HierarchyViewer/components/MainPanel.tsx
- src/features/HierarchyViewer/components/SubNetworkPanel.tsx
- src/features/HierarchyViewer/store/ndexQueryFetcher.ts
- src/models/FilterModel/DisplayMode.ts
- src/models/FilterModel/Filter.ts
- src/models/FilterModel/FilterConfig.ts
- src/models/FilterModel/FilterUi.ts
- src/models/FilterModel/FilterUiProps.ts
- src/models/FilterModel/FilterWidgetType.ts
- src/models/FilterModel/SelectionType.ts
- src/models/FilterModel/impl/SimpleFilter.ts
- src/models/FilterModel/index.ts
- src/models/TableModel/impl/NetworkAttributesImpl.ts
- src/store/FilterStore.ts
- src/store/ViewModelStore.ts
- src/store/persist/db.ts
- src/utils/cx-utils.ts
This includes the following:
- Basic filter models
- Implementation of a UI based on the model
- Store for the filter
The UI is only for the Hierarchy viewer, and not enabled for other networks.
> Basic Discrete Filter

- src/features/MergeNetworks/components/MergeDialog.tsx
- src/features/MergeNetworks/models/Impl/CreateMergedNetworkWithView.ts
Solved two bugs:
1. A toggle button bug: [Jira ticket](https://cytoscape.atlassian.net/browse/CW-206)
2. A visual style bug: the visual style cannot be fetched from the store successfully if the network was not pre-loaded in the workspace, now I directly fetch the visual style information from the database
> Solved a visual style and a toggle button bug

- src/components/LayoutTools/Scaling.tsx
- src/components/NetworkPanel/NetworkPanel.tsx
This will fix the position reset problem described in CW-209.
> CW-209 Changed to update whenever view model has new updates

- package-lock.json
- package.json
- src/AppConfigContext.ts
- src/assets/config.json
- src/components/ToolBar/DataMenu/LoadFromNdexDialog.tsx
- src/index.tsx
- add config value
- up the limit of my networks for the load from ndex modal
> add google analytics

- src/components/SummaryPanel/NetworkPropertyPanel.tsx
> Add confirmation window

- src/components/Vizmapper/index.tsx
Original Ticket: [CW-230](https://cytoscape.atlassian.net/browse/CW-230)
[CW-230]: https://cytoscape.atlassian.net/browse/CW-230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Height Adjust

- src/features/TableDataLoader/components/CreateNetworkFromTable/TableColumnAssignmentForm.tsx
- src/features/TableDataLoader/components/JoinTableToNetwork/TableColumnAppendForm.tsx
- src/features/TableDataLoader/model/impl/ParseValues.ts
- when the user loads a data table, try to guess the data type for each column
> auto detect column types in the table data loader

- src/components/AppShell.tsx
- src/components/Workspace/WorkspaceEditor.tsx
- Cleaned up the initialization process
- Added initialization flag in WorkspaceEditor to avoid unnecessary reset and navigation caused by empty workspace checker
> CW-237 Fixed unnecessary navigation and reset

- src/components/LayoutTools/Scaling.tsx
- src/components/LayoutTools/scaling-util.ts
Scaling will be applied correctly when moving slider.
> CW-209 Fixed scaling problem by blocking unnecessary initialization.

- package-lock.json
- src/features/HierarchyViewer/components/CustomLayout/CirclePackingPanel.tsx
In addition to scaling and displacement, correct delta has been added to both width and height.
This should always place the circle to the center whenever the fit content is called.
> CW-261 Correct displacement has been added to Circle wrapper

- src/assets/config-test.txt
- src/features/HierarchyViewer/components/CustomLayout/CirclePackingPanel.tsx
When user click outside of the circle, it will clear the selection in both CP and in the interaction network.
> Clear selection functions implemented for CP

- src/components/TableBrowser/TableBrowser.tsx
use lodash orderBy instead of a custom sorting implementation
> fix issue where sorting table columns would not work

- src/store/WorkspaceStore.ts
In addition to single deletion, the function accepts array of IDs, too.
> Now delete accepts both single value or array of IDs

- src/components/Login/LoginButton.tsx
|Case| Redirect Url|
|-|-|
| Localhost| localhost:5500/ |
| Test Server| idekerlab.ndexbio.org/cytoscape/|
> Resolved the redirection bug when logging out 

- src/models/VisualStyleModel/VisualPropertyValue/NodeShapeType.ts
> Resolved the bug of Rendering Shape Parallelogram

- src/components/ToolBar/DataMenu/SaveWorkspaceToNDEx.tsx
> Fix CW-272

- src/models/VisualStyleModel/impl/VisualStyleFnImpl.ts
- src/models/VisualStyleModel/impl/compute-view-util.ts
- fix issue where node label position is not rendered properly the first time it is rendered
- fix issue where bypasses were not being imported properly
> node label position bug fix

- src/components/ToolBar/DataMenu/ExportNetworkToImage/ExportNetworkToImageMenuItem.tsx
- src/components/ToolBar/DataMenu/ExportNetworkToImage/PdfExportForm.tsx
- src/components/ToolBar/DataMenu/ExportNetworkToImage/PngExportForm.tsx
- src/components/ToolBar/DataMenu/ExportNetworkToImage/SvgExportForm.tsx
|Type|Display|
| -------- | ------- |
|PNG|<img width="450" alt="image" src="https://github.com/user-attachments/assets/7636885f-30d7-4b21-b623-9a37e6cbb5da">|
|SVG|<img width="450" alt="image" src="https://github.com/user-attachments/assets/a0491b9a-3fb0-4ca6-ad16-e0db52d798d5">|
|PDF|<img width="450" alt="image" src="https://github.com/user-attachments/assets/18b4b6e5-b20f-4b1e-a2aa-c5215be4bcf7">|
> Improve look and feel of the image exporter window

- src/components/Vizmapper/index.tsx
Jira: [CW-299](https://cytoscape.atlassian.net/browse/CW-299)
1.Discard the 'i' icon for the Node/Edge labels' tooltip
2. Make sure the tooltips of 'lockable' properties do not overlap
[CW-299]: https://cytoscape.atlassian.net/browse/CW-299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Tooltip UI in Vizmapper

- src/assets/config.json
- src/components/Vizmapper/Forms/BypassForm.tsx
When bypass values are listed in the modal dialog box, the name of the selected nodes (or edges) are given in the following order:
1. Style - (Node/Edge) Label - **Bypass Value**
2. Style - (Node/Edge) Label - **Mapping Value**
3. Style - (Node/Edge) Label - **Default Value**
4. The value of the attribute called '**name**'(if it exists)
5. The node/edge **Id**
Namely: Label Value > Name Attribute > Id
|Name source|Example|
|---------|---------|
|Bypass Value|<img width="500" alt="image" src="https://github.com/user-attachments/assets/e9ceb3be-6878-4e31-aa73-14d5484c05ca">|
|Mapping Value|<img width="500" alt="image" src="https://github.com/user-attachments/assets/e9077d39-132a-4266-9fbe-37c022669927">|
|Default Value|<img width="500" alt="image" …
> Node/Edge Naming in the bypass form

- src/assets/config.json
- src/components/Vizmapper/VisualPropertyRender/Number.tsx
- src/models/VisualStyleModel/VisualProperty.ts
- src/models/VisualStyleModel/impl/DefaultVisualStyle.ts
Jira: [CW-37](https://cytoscape.atlassian.net/browse/CW-37)
Added the check for the value range, now only the value in the range of **[0,1000)**  is considered as valid
[CW-37]: https://cytoscape.atlassian.net/browse/CW-37?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Improve number validator

- src/assets/config.json
- src/components/AppShell.tsx
- src/components/SummaryPanel/Summaries.tsx
- src/components/TableBrowser/NetworkInfoPanel.tsx
- src/components/TableBrowser/TableBrowser.tsx
- src/components/ToolBar/ToolBar.tsx
- src/components/Workspace/NetworkBrowserPanel/NetworkBrowserPanel.tsx
- src/components/Workspace/NetworkBrowserPanel/WorkspaceNamePanel.tsx
- src/components/Workspace/WorkspaceEditor.tsx
- src/index.css
- src/store/persist/db.ts
New workspace name panel has been added and layout of all UI components are tweaked to keep consistent spacing after adding new components.
> Workspace name editor with overhauled workspace UI layouts

- src/store/TableStore.ts
- splice only 1 element instead of all elements after start index
> fix bug where all table columns after the column to delete would be deleted

- src/Error.tsx
- src/components/ToolBar/DataMenu/LoadWorkspaceDialog.tsx
- src/components/ToolBar/DataMenu/ResetLocalWorkspace.tsx
- src/components/Workspace/WorkspaceEditor.tsx
- src/models/StoreModel/WorkspaceStoreModel.ts
- src/store/WorkspaceStore.ts
Now the delete DB function is always called before returning the new state.
> Made the resetWorkspace function synchronous

- src/components/ToolBar/DataMenu/LoadFromNdexDialog.tsx
- src/components/ToolBar/DataMenu/LoadWorkspaceDialog.tsx
- src/components/ToolBar/DataMenu/LoadWorkspaceMenuItem.tsx
- src/components/ToolBar/DataMenu/SaveWorkspaceToNDEx.tsx
- src/components/ToolBar/DataMenu/SaveWorkspaceToNDExOverwrite.tsx
- src/store/io/exportCX.ts
- src/store/persist/db.ts
- src/utils/ndex-utils.ts
1. Solved 'Save workspace as...' bug: users can save the workspace(create a new entry)
2. Solved 'Save workspace' bug: users can save/overwrite the current workspace
3. Solved 'Load workspace from NDEx' bug: users can load the remote workspace and overwrite the local workspace
> Solved Workspace-related Bugs

- src/components/Vizmapper/VisualPropertyRender/NodeLabelPosition.tsx
- src/models/VisualStyleModel/impl/nodeLabelPositionMap.ts
- users can choose 9 preset orientations, choose a text justification from a dropdown and set the x and y margin offsets
> update node label position form

- src/components/FloatingToolBar/ShareNetworkButtton.tsx
> Fix bug where network selection states are not in sync with the network url

- src/components/TableBrowser/TableBrowser.tsx
- src/store/TableStore.ts
Jira: [CW-324](https://cytoscape.atlassian.net/browse/CW-324)
[CW-324]: https://cytoscape.atlassian.net/browse/CW-324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Let update on the node/edge table mark the network as modified

- src/components/FloatingToolBar/FitButton.tsx
- src/components/NetworkPanel/CyjsRenderer/CyjsRenderer.tsx
- src/components/Workspace/NetworkBrowserPanel/NetworkBrowserPanel.tsx
- src/features/LLMQuery/components/LLMQueryResultPanel.tsx
- fix issue where llm query panel could not scroll 
- fix issue where networks would not be fit to the screen after initial render
> Fixes for leah demo

- src/components/ToolBar/AnalysisMenu/index.tsx
- src/components/ToolBar/DataMenu/index.tsx
- src/components/ToolBar/LayoutMenu/index.tsx
- src/components/ToolBar/ToolsMenu/index.tsx
- this change is needed to support inserting apps in specific locations in nested menus
- the apps menu will be changed to be a tiered menu at a later point
> Analysis, layout and tools menus use tiered menus

- src/components/FloatingToolBar/ApplyLayoutButton.tsx
- src/components/FloatingToolBar/FitButton.tsx
- src/components/FloatingToolBar/FloatingToolBar.tsx
- src/features/HierarchyViewer/components/SubNetworkPanel.tsx
- disable fit and layout buttons for the circle packing view
- fix issue where the subsystem text would be overlayed on top of dialogs
> Fix hiview bugs

- src/components/FloatingToolBar/FitButton.tsx
- src/components/FloatingToolBar/FloatingToolBar.tsx
- src/components/NetworkPanel/NetworkTabs.tsx
- src/components/ToolBar/LayoutMenu/index.tsx
- src/models/StoreModel/UiStateStoreModel.ts
- src/models/UiModel/NetworkViewUI.ts
- src/models/UiModel/Ui.ts
- src/store/UiStateStore.ts
- Fix bug where the fit function wouldn't work for the cell view
- Disable the layout menu when the current network is a hcx network, the root network is the activeNetwork, and the cell view tab is selected
> Fix hiview layout menu

- src/models/AppModel/ServiceAppTask.ts
- src/models/AppModel/ServiceStatus.ts
- src/models/StoreModel/AppStoreModel.ts
- src/store/AppStore.ts
Store updated to keep track of the running task.
> Running task status store updated

- package-lock.json
- src/assets/test-service-definition.json
- src/models/AppModel/ColumnTypeFilter.ts
- src/models/AppModel/ParameterUiType.ts
- src/models/AppModel/ServiceAppParameter.ts
- src/models/AppModel/ServiceMetadata.ts
- src/models/AppModel/ValidationType.ts
The Service App models are updated to support multiple actions as a ordered list.
> Parameter object defined and actions are now list, not string.

- src/components/ToolBar/HelpMenu/TutorialMenuItem.tsx
- src/components/ToolBar/HelpMenu/index.tsx
https://cytoscape.atlassian.net/browse/CW-366
> update Help menu

- src/components/ToolBar/DataMenu/ExportNetworkToImage/PngExportForm.tsx
Jira Ticket:  [CW-355](https://cytoscape.atlassian.net/browse/CW-355)
[CW-355]: https://cytoscape.atlassian.net/browse/CW-355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Export network to PNG: Set zoom default value to 100%

- src/components/ToolBar/DataMenu/ExportNetworkToImage/PngExportForm.tsx
https://cytoscape.atlassian.net/browse/CW-354
> fix typo on export image

- src/components/ToolBar/AppMenu/menu-factory.tsx
- src/models/AppModel/ServiceInputDefinition.ts
- src/models/AppModel/impl/index.ts
- src/models/StoreModel/AppStoreModel.ts
- src/store/AppStore.ts
Renders a dialog box when the user clicks a service menu app item. 
Renders an node/edge column selector for each InputColumn model when the service input type is node or edge.
Render various parameter types for any service app.
Todo:
- Using validation regex
- Filtering columns by data type
> Add basic parameter UI

- package-lock.json
- src/App.tsx
- src/bootstrap.tsx
- src/components/EmailVerification.tsx
> Email Verification

- src/components/ToolBar/DataMenu/ExportNetworkToImage/ExportNetworkToImageMenuItem.tsx
Ticket: [CW-360](https://cytoscape.atlassian.net/browse/CW-360)
Use the network name as the default export file name:
[CW-360]: https://cytoscape.atlassian.net/browse/CW-360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Default Network Name for Exportation

- package-lock.json
- package.json
- src/bootstrap.tsx
- src/components/EmailVerification.tsx
- src/components/ToolBar/DataMenu/SaveToNDExMenuItem.tsx
1. Used signInFromIdToken() instead
2. Make suer the app would not hit the route and only show the notification dialog when the user's email is not verified
Set the tooltip for case when a user is not loggedin
> Replaced getSignedInUser() with signInFromIdToken()

- src/components/LayoutTools/LayoutToolsPanel.tsx
- src/components/LayoutTools/Scaling.tsx
For ticket: [CW-361](https://cytoscape.atlassian.net/browse/CW-361)
[CW-361]: https://cytoscape.atlassian.net/browse/CW-361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Layout Tools: Fixed width or height only scaling

- src/components/ToolBar/ToolsMenu/index.tsx
Ticket:[CW-392](https://cytoscape.atlassian.net/browse/CW-392)
[CW-392]: https://cytoscape.atlassian.net/browse/CW-392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Close Menu Item after closing the Merge Dialog

- src/components/NetworkPanel/CyjsRenderer/CyjsRenderer.tsx
- src/components/NetworkPanel/NetworkTab.tsx
- src/components/NetworkPanel/NetworkTabs.tsx
- src/models/RendererModel/Renderer.ts
- src/store/DefaultRenderer.tsx
Ticket: [CW-340](https://cytoscape.atlassian.net/browse/CW-340)
|After fix| Before fix|
|------|------|
|<img width="450" alt="image" src="https://github.com/user-attachments/assets/5ad571a8-c10b-476d-83d7-872afc8e3d44">|<img width="450" alt="image" src="https://github.com/user-attachments/assets/a5310732-1e19-4672-b18b-eb3370ae0ffd">|
[CW-340]: https://cytoscape.atlassian.net/browse/CW-340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix the improper position of 'Applying Layout'

- src/features/HierarchyViewer/components/CustomLayout/CirclePackingLayout.ts
- src/features/HierarchyViewer/components/CustomLayout/DataBuilderUtil.ts
- src/utils/ndex-utils.ts
When member IDs (integers) are available, it will be correctly converted to the name using external service.
> Fixed wrong index for ID conversion from membership list

- src/components/TableBrowser/NetworkInfoPanel.tsx
Ticket: [CW-412](https://cytoscape.atlassian.net/browse/CW-412)
[CW-412]: https://cytoscape.atlassian.net/browse/CW-412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add UUID display

- src/Error.tsx
- src/components/ToolBar/DataMenu/ResetLocalWorkspace.tsx
- src/store/WorkspaceStore.ts
- src/store/persist/db.ts
I think the DB deletion and reload timing causes the problem. To avoid it, some error handlers and waits has been added before reloading the entire workspace.
> Added some safety function calls and waits to create a clean slate.

- src/components/NetworkPanel/CyjsRenderer/CyjsRenderer.tsx
- src/components/NetworkPanel/CyjsRenderer/cyjs-util.ts
Moved the position of edge selected color entry to the end of style to provide the highest priority when calculating style in Cyjs.
> CW-317 Resolved edge selected color problem

- src/assets/apps-dev.json
- src/assets/apps.json
There are two config files for the app location:
- apps.json: This is the one containing app URLs in production server
- apps-dev.json: If you need to develop apps locally, this should be used.
> Default config files are now pointing to the example apps on GitHub

- src/components/ToolBar/LicenseMenu/LicenseDialog.tsx
- src/components/ToolBar/LicenseMenu/index.tsx
- src/components/ToolBar/ToolBar.tsx
> Add License

- src/components/FloatingToolBar/OpenInCytoscapeButton.tsx
- src/components/ToolBar/DataMenu/CopyNetworkToNDExMenuItem.tsx
- src/components/ToolBar/DataMenu/DownloadNetworkMenuItem.tsx
- src/components/ToolBar/DataMenu/OpenNetworkInCytoscapeMenuItem.tsx
- src/components/ToolBar/DataMenu/SaveToNDExMenuItem.tsx
- src/components/ToolBar/DataMenu/SaveWorkspaceToNDEx.tsx
- src/components/ToolBar/DataMenu/SaveWorkspaceToNDExOverwrite.tsx
- src/components/ToolBar/FileUpload.tsx
- src/features/ServiceApps/index.ts
- src/store/hooks/useNdexNetwork.ts
- src/store/hooks/useServiceTaskRunner.ts
- src/store/io/exportCX.ts
- src/utils/cx-utils.ts
- src/utils/ndex-utils.ts
Export opaque aspects for various cx2 network creations methods (download cx2, save to ndex, save to workspace, service apps)
> Export opaque aspects

- src/components/Vizmapper/Forms/BypassForm.tsx
Ticket: [CW-435](https://cytoscape.atlassian.net/browse/CW-435)
[CW-435]: https://cytoscape.atlassian.net/browse/CW-435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add 'Remove All Bypasses' Button

- src/components/Vizmapper/index.tsx
- src/models/VisualStyleModel/impl/DefaultVisualStyle.ts
Ticket: [CW-439](https://cytoscape.atlassian.net/browse/CW-439)
[CW-439]: https://cytoscape.atlassian.net/browse/CW-439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add tooltips for Visual Property

- src/components/LayoutTools/ScalingTypeSelector.tsx
Simple fix for the warning messages.
> CW-453: Keys have been added to the child components

- src/components/Vizmapper/Forms/MappingForm/ContinuousMappingForm/ContinuousColorMappingForm.tsx
- src/components/Vizmapper/Forms/MappingForm/ContinuousMappingForm/ContinuousNumberMappingForm.tsx
- src/components/Vizmapper/Forms/MappingForm/index.tsx
- src/store/VisualStyleStore.ts
- Rework gt/lt controls in the color and number form
- Fix issue where the color schemes were not applied properly (cold/hot values swapped)
- Fix issue where middle handle was not positioned in the mid point when creating a continuous mapping
> Fix various issues in the continuous mapping form

- src/components/ToolBar/DataMenu/CopyNetworkToNDExMenuItem.tsx
- src/components/ToolBar/DataMenu/SaveToNDExMenuItem.tsx
- src/components/ToolBar/DataMenu/SaveWorkspaceToNDEx.tsx
- src/components/ToolBar/DataMenu/SaveWorkspaceToNDExOverwrite.tsx
- src/components/ToolBar/DataMenu/index.tsx
- src/components/ToolBar/FileUpload.tsx
- src/components/Vizmapper/Forms/MappingForm/index.tsx
- src/models/NetworkWithViewModel/NetworkWithView.ts
- src/models/StoreModel/VisualStyleStoreModel.ts
- src/models/VisualStyleModel/VisualMappingFunction/VisualMappingFunction.ts
- src/models/VisualStyleModel/impl/VisualStyleFnImpl.ts
- src/models/VisualStyleModel/impl/cxVisualPropertyConverter.ts
- src/store/io/exportCX.ts
- src/store/persist/db.ts
- src/utils/CachedData.ts
- src/utils/cx-utils.ts
- src/utils/ndex-utils.ts
Reverts cytoscape/cytoscape-web#371
> Revert "Resolved U2OS losing layout bug"

- src/components/ToolBar/FileUpload.tsx
- Use safe checks for accessing network attributes.
- Remove unsafe logic for accessing name and description from cx.
- Add a check in the node position aspect to see if the network already has a layout and set the flag in the network summary accordingly.
- If the name doesn't exist in the file attributes, use the same logic for creating a name for the network when a user creates a network from a table.
> Fix bugs related to cx2 file upload

- src/components/FloatingToolBar/OpenInCytoscapeButton.tsx
- src/components/ToolBar/DataMenu/OpenNetworkInCytoscapeMenuItem.tsx
disable this menuitem when browser is safari
> fix open in cytoscape menuitem in data menu

- src/components/TableBrowser/NetworkInfoPanel.tsx
Previously, we only listened for changes to tables, networkView, and visualStyle.
However, one area was overlooked:
Users can click the 'pencil' icon to edit network properties, as shown below:
After the click, the dialog would show and we also need to listen for changes to network names, descriptions and properties:
> Mark network as IsModified when name, description or properties are changed

- src/components/ToolBar/DataMenu/CopyNetworkToNDExMenuItem.tsx
- src/components/ToolBar/DataMenu/SaveToNDExMenuItem.tsx
- src/components/ToolBar/DataMenu/SaveWorkspaceToNDEx.tsx
- src/components/ToolBar/DataMenu/SaveWorkspaceToNDExOverwrite.tsx
- src/store/hooks/useServiceTaskRunner.ts
- src/store/io/exportCX.ts
- src/utils/ndex-utils.ts
|To test, follow the steps |
|-----|
|1. Import one or more cx2 file to the current workspace|
|<img width="700" alt="image" src="https://github.com/user-attachments/assets/bddb12fa-90a7-4cdd-8acf-3c26cdfbf000" />|
|2. Click "Save Workspace as" in the **Data** menu and enter a unique workspace name|
|<img width="700" alt="image" src="https://github.com/user-attachments/assets/2962d139-faa1-4e9f-8e5d-023c42c69454" />|
|3. Click 'Save'|
|<img width="700" alt="image" src="https://github.com/user-attachments/assets/f2d13c59-83ac-4984-a9d5-3796522a84e1" />|
|4. Check the workspace status in "Data -> Open Workspace from NDEx..."|
|<img width="700" alt="Screenshot 2025-01-12 at 3 35 48 PM" src="https://github.com/user-attachments/assets/85c9c6c4-fef6-47a6-a144-84f786941465" />|
* This PR …
> Delete the original network when saving copy of a network

- src/components/FloatingToolBar/ShareNetworkButtton.tsx
https://cytoscape.atlassian.net/browse/CW-487
> Disable share network button when the current network is local cx2

- src/components/ToolBar/AppMenu/index.tsx
- src/components/ToolBar/DataMenu/LoadWorkspaceDialog.tsx
- src/components/ToolBar/DataMenu/SaveWorkspaceToNDEx.tsx
- src/components/ToolBar/DataMenu/SaveWorkspaceToNDExOverwrite.tsx
Ticket: [CW-480](https://cytoscape.atlassian.net/browse/CW-480)
[CW-480]: https://cytoscape.atlassian.net/browse/CW-480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Save App to Workspace

- src/store/io/exportCX.ts
Ticket: [CW-477](https://cytoscape.atlassian.net/browse/CW-477)
Entries for **description** and **version** in `networkAttributes` are manually populated based on non-empty values provided in the `summary`
- Load a network in Cy-web, and changes its name, version, description or network properties in the dialog, which is opened by clicking the 'pencil' icon
- Save the current network to NDEx by clicking ‘Data → Save Network to NDEx’
- Clear the current workspace by clicking 'Datat → Clear the Local Database'
- Load the network from NDEx you saved just now and check whether the network name, version, description and propties are exactly the same
[CW-477]: https://cytoscape.atlassian.net/browse/CW-477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …
> Fix CX2 export bug on Description and Version

- src/components/TableBrowser/NetworkInfoPanel.tsx
- src/components/ToolBar/DataMenu/LoadWorkspaceDialog.tsx
- src/components/Workspace/NetworkBrowserPanel/WorkspaceNamePanel.tsx
- src/utils/date-format.ts
Ticket: [CW-509](https://cytoscape.atlassian.net/browse/CW-509)
| Before | Now |
| -------| -------|
|<img width="400" alt="image" src="https://github.com/user-attachments/assets/9912c521-0571-4915-bdbb-ec3f059aef3e" />|<img width="400" alt="image" src="https://github.com/user-attachments/assets/d9524f44-f076-498b-8702-c1c4755f2b7e" />|
[CW-509]: https://cytoscape.atlassian.net/browse/CW-509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DateFormatter debug

- src/components/ToolBar/HelpMenu/BugReportMenuItem.tsx
https://cytoscape.atlassian.net/jira/software/projects/CW/issues/CW-515
This is only a temporary fix. To add tags or prefix, we have to generate a new script here: https://cytoscape.atlassian.net/secure/AddCollector!edit.jspa?projectKey=CSD&collectorId=45488c8f
But since we share the bug report collector with Cytoscape Service Desk, should we create a new one for Cyweb?
> Fix CW-515

- src/components/ToolBar/DataMenu/ExportNetworkToImage/ExportNetworkToImageMenuItem.tsx
- src/components/ToolBar/DataMenu/ExportNetworkToImage/PdfExportForm.tsx
- src/components/ToolBar/DataMenu/ExportNetworkToImage/PngExportForm.tsx
- src/components/ToolBar/DataMenu/ExportNetworkToImage/SvgExportForm.tsx
Ticket: [CW_525](https://cytoscape.atlassian.net/browse/CW-525)
- Move the Cancel and Confirm buttons from the individual export form(svg, png and pdf) components to the root dialog
- Modify each export form to return their settings and expose a save function so that the root dialog can call each different save function
> Anchor 'cancel' and 'confirm' in Export Network Dialog

- src/features/HierarchyViewer/components/SubNetworkPanel.tsx
- src/features/HierarchyViewer/workers/cpLayoutWorker.ts
This pull request includes major changes to the `SubNetworkPanel` component in the `src/features/HierarchyViewer` directory to improve the UI responsiveness and handle long-running operations using asynchronous processing and web workers. The most important changes include the addition of state variables for tracking processing progress, the implementation of a helper function to yield control back to the UI thread, the reintroduction of the `getCpViewModel` function, and the use of a web worker for layout calculations.
Improvements to UI responsiveness:
* [`src/features/HierarchyViewer/components/SubNetworkPanel.tsx`](diffhunk://#diff-ba1207fa145f0f7cc19dfd19175272b40b4b4896f66bb12ce6075ffa7c484278R74-R90): Added state variables `isProcessing`, `processingProgress`, and `processingStage` …
> Fix for Hiview's UI Blocking Problem

- src/components/ToolBar/FileUpload.tsx
- src/features/TableDataLoader/components/CreateNetworkFromTable/TableColumnAssignmentForm.tsx
- src/features/TableDataLoader/components/JoinTableToNetwork/TableUpload.tsx
This pull request refines network file upload functionality, enhances error handling, and code cleanups across multiple components. Key changes include better validation for file formats, improved error messages, and minor code refactoring for clarity.
The major change for the D&D feature is deletion of accept / reject icons in the window due to the library's bug for custom file types (see details below). 
* Added better validation for file types in `FileUpload` to detect unsupported formats, mismatched extensions, and invalid content (e.g., `.csv` without commas). Enhanced error messages to provide clearer guidance on supported formats and issues. (`src/components/ToolBar/FileUpload.tsx`, [[1]](diffhunk://#diff-7d0beffdad403ef1ccaf0042f5754b051222cdd8e8162df729ac32bc5adfd364R210-R276) …
> Improved network file drag & drop and bug fixes

- src/components/ToolBar/FileUpload.tsx
Show an error message to the users if they upload multiple files in the file upload modal
Refs #CW-555
> Fix issue where multiple files could be uploaded in the file upload modal

- src/components/ToolBar/HelpMenu/CitationMenuItem.tsx
Updated the citation text. Using on button to copy both citations to clipboard. Improve styling of the citation text. Refactored the code to be more maintainable and optimized for bundle size.
> Fix CW-571. Updated citation text and refactor the code of citation window.

- src/components/AppShell.tsx
- src/components/ToolBar/DataMenu/LoadFromNdexDialog.tsx
- src/store/hooks/useUrlNavigation/url-manager.ts
This pull request focuses on cleaning up debug logs, improving code readability, and ensuring robustness in handling undefined values. The most important changes include removing or commenting out unnecessary debug logs, handling undefined values for `subnetworkIds`, and switching to `console.debug` for a more appropriate logging level.
This resolves the crash problem when user clicks the Data menu.
* Removed or commented out extensive debug logging related to React Router location changes in `AppShell` to reduce noise in the console. (`src/components/AppShell.tsx`)
* Changed a `console.log` statement to `console.debug` for history debug information in `url-manager.ts` to better align with logging conventions. (`src/store/hooks/useUrlNavigation/url-manager.ts`)
* Commented out verbose …
> Fixed crash problem when user clicks Data menu

- src/components/TableBrowser/TableBrowser.tsx
Fixed https://cytoscape.atlassian.net/browse/CW-603 by adding z-index.
> Fix CW-603
