- src/components/TableBrowser/TableBrowser.tsx
- src/models/TableModel/Column.ts
- src/models/TableModel/impl/InMemoryTable.ts
Instead of storing defaultValue in the column model, apply the default value to each row if necessary and then do not store the default value in the column model any more.
> Remove the concept of 'defaultValue' for columns

- src/components/Vizmapper/Forms/MappingForm/index.tsx
- src/models/VisualStyleModel/impl/MappingFunctionImpl.ts
- disable continuous mapping functions for the visual properties that do not support it and provide a tooltip stating why it is disabled
- rename 'attribute' to 'column' for all the lines of code I touched to eventually remove all uses of 'attribute'
- when the user clicks a attribute, filter the mapping types based on the type of the attribute
- when a user clicks a mapping type, filter the attributes based on the ones that are compatible with the mapping type
> slightly improve ux for the mapping form

- src/components/SummaryPanel/NetworkPropertyPanel.tsx
- src/components/ToolBar/DataMenu/CopyNetworkToNDExMenuItem.tsx
- src/components/ToolBar/DataMenu/LoadFromNdexMenuItem.tsx
- src/components/ToolBar/DataMenu/SaveToNDExMenuItem.tsx
- src/components/Workspace/WorkspaceEditor.tsx
- sometimes calling setCurrentNetworkId would not change the network properly because of a useEffect that would always set the current network id to the first network id in the workspace
- change this behaviour to only set the current network id if it is not set yet.
> fix issues with setting the current network id

- src/components/NetworkPanel/CyjsRenderer/CyjsRenderer.tsx
- src/components/NetworkPanel/CyjsRenderer/cyjs-util.ts
- src/models/NetworkModel/impl/CyNetwork.ts
- src/models/VisualStyleModel/impl/compute-view-util.ts
- src/store/ViewModelStore.ts
- fix issues where hoveredElement and selectedNodes and selectedEdges were not being persisted across networkView updates
- implement applyHoverUpdate() in the cy.js renderer which applies hover styles when hoveredElement changes
> Fix bypass UI hover

- .eslintrc.json
- package-lock.json
- package.json
- src/components/AppShell.tsx
- src/components/NetworkPanel/CyjsRenderer/CyjsRenderer.tsx
- src/components/SummaryPanel/NetworkPropertyPanel.tsx
- src/components/ToolBar/DataMenu/SaveToNDExMenuItem.tsx
- src/components/Workspace/WorkspaceEditor.tsx
- src/store/NetworkStore.ts
- src/store/NetworkSummaryStore.ts
- src/store/TableStore.ts
- src/store/ViewModelStore.ts
- src/store/VisualStyleStore.ts
- src/store/WorkspaceStore.ts
- src/store/useNdexNetworkSummary.ts
- fix bug related to hoveredElement being undefined in the `applyHoverUpdate()` function
- rework the network summary ui to be a popover instead of a accordion
- network modified indicator appears when the visual style/table/network model changes
- subscribe to the viewModelStore and diff the computed views to determine if they have changed using lodash `isEqual()`
- refactor stores to use a persist middleware function that saves the model to the cache every time a store function is called.
- refactor network summary store to make it's api more consistent with the other store.  Move caching/network request logic into the `useNdexNetworkSummary` module
-  code that gets ndex network summaries and ndex networks now follow the same code pattern (check cache for the object, if it is not found …
> Network modified and model save

- src/components/TableBrowser/TableBrowser.tsx
- src/components/Vizmapper/Forms/BypassForm.tsx
- src/components/Vizmapper/Forms/MappingForm/ContinuousMappingForm/ContinuousColorMappingForm.tsx
- src/components/Vizmapper/Forms/MappingForm/index.tsx
Addresses some of the feedback received by Dexter/Rudi.
1. remove the '+' symbol for empty mapping visual properties to be consistent with the rest of the vizmapper forms/elements
2. make it less likely that the user will accidentally click the delete button in a continuous mapping color picker handle when they wanted to instead click on the color picker
3. filter the table rows based on the selected nodes/edges in the network
4. remove the feature that highlighted the node/edge when hovering over a table row or a element in the bypass map
> ui feedback

- src/components/TableBrowser/TableBrowser.tsx
- src/components/TableBrowser/TableColumnForm.tsx
- src/components/Vizmapper/Forms/MappingForm/index.tsx
- src/components/Vizmapper/Forms/VisualPropertyValueForm.tsx
- src/components/Vizmapper/VisualPropertyRender/HorizontalAlign.tsx
- src/models/TableModel/impl/InMemoryTable.ts
- src/models/VisualStyleModel/VisualPropertyValueTypeName.ts
- src/models/VisualStyleModel/impl/MappingFunctionImpl.ts
- src/store/TableStore.ts
- Add table browser functions in the table store to create/edit/delete columns
- Show a button group of actions that can be performed by the user when they click a cell or a header
- Specific functions added: create/edit/delete column, apply value to column, apply value to selected nodes
In another PR I will try to make these menus show in a context menu via right click.  I was not able to get it working at the moment.
> Table browser features

- src/features/HierarchyViewer/utils/hierarcy-util.ts
- return undefined if the summary object is empty in the hcx utils
refs #CW-95
> fix bug that broke the app when a network with an empty summary was loaded

- src/models/VisualStyleModel/impl/MapperFactory.ts
- normalize values when a passthrough mapping is defined for a enum visual property type
- e.g. Rectangle/RECTANGLE/rectangle are all valid values for a shape passthrough
- define logic in the mapping factory to determine if we should normalize the value (turn the string to lowercase)
> Make passthrough mapping logic more consistent with Cytoscape Desktop

- src/components/NetworkPanel/CyjsRenderer/cyjs-util.ts
- src/models/VisualStyleModel/VisualPropertyName.ts
- src/models/VisualStyleModel/impl/CyjsProperties/CyjsVisualPropertyName.ts
- src/models/VisualStyleModel/impl/DefaultVisualStyle.ts
- src/models/VisualStyleModel/impl/cxVisualPropertyConverter.ts
- src/models/VisualStyleModel/impl/cyJsVisualPropertyConverter.ts
- also add 'text-wrap' to be 'wrap' by default in the cyjs renderer
refs #CW-69
> add nodeMaxLabelWidth and edgeMaxLabelWidth visual properties

- src/components/TableBrowser/TableBrowser.tsx
- src/components/TableBrowser/TableColumnForm.tsx
- src/store/VisualStyleStore.ts
- src/utils/is-url.ts
When a user renames or deletes a column, provide a radio button group that gives them option on how to handle columns that are used in visual style mappings.  
The options are:
1. delete the mapping
2. update the mapping with newly renamed column
3. do nothing (with a warning saying that invalid vizmapper state will produce errors when saving to NDEx)
> Column edit choices

- src/components/NetworkPanel/NetworkPanel.tsx
- src/components/TableBrowser/TableBrowser.tsx
- src/components/Workspace/WorkspaceEditor.tsx
- src/store/UiStateStore.ts
- fix bug where 'applying layout...' would display indefinitely after running a layout on a network that didn't have a layout
- disable popup when clicking nodes/edges in the network view
- add table browser index setting as a search parameter
- fix expand/collapse table browser button
> Misc fixes

- src/features/HierarchyViewer/components/MainPanel.tsx
- src/features/HierarchyViewer/components/SubNetworkPanel.tsx
- src/features/HierarchyViewer/store/ndexQueryFetcher.ts
- src/features/HierarchyViewer/store/useHierarchyViewerManager.tsx
- src/store/persist/db.ts
This change addresses the possibility of ID conflicts within interaction networks in the database, and it also solves the issue of cleaning up when the parent network is deleted.
> Fixes for CW 122 and 123

- src/App.tsx
- src/components/FloatingToolBar/ShareNetworkButtton.tsx
The /network endpoint has been removed. Now "0" will be used as a dummy workspace ID.
> Network sharing route has been updated to use dummy WS ID.

- src/components/AppShell.tsx
- routing logic used to assume that the network id exists in the workspace.  changed it to always add the network id to the workspace
> fix bugs related to loading networks from  url

- src/features/HierarchyViewer/store/useHierarchyViewerManager.tsx
- src/store/hooks/useWorkspaceManager.ts
- reset active network view if the active network view id in the ui state store matches any hierarchy children to be deleted
- reset active network view id in the ui state store if it matches any of the networks to be deleted
> reset active network view when networks are deleted

- src/features/LLMQuery/components/LLMQueryOptionsMenuItem.tsx
- src/features/LLMQuery/components/LLMQueryResultPanel.tsx
- src/features/LLMQuery/components/RunLLMQueryMenuItem.tsx
- dont show default llm keys in the textfield
- llm key field only changes the key when the user enters input, it does nothing if it is empty
- disable regenerate response button when the gene query string is empty
- show warning message when genes were not found in the hcx related columns (members/memberNames)
> Llm empty query

- src/features/HierarchyViewer/components/SubNetworkPanel.tsx
- src/models/ViewModel/NetworkView.ts
- src/store/ViewModelStore.ts
- src/store/persist/db.ts
- unittest/store/ViewModelStore.test.ts
From this version, _viewId_ will be assigned to the view models in the NetworkView array in the store.
This resolves the bug generating duplicate network view models in the store
> Fix for duplicate view models bug

- src/components/AppShell.tsx
Simple fix to avoid unnecessary warning dialog for the workspace ID for sharing ('0').
> 0 will be used as a valid dummy workspace ID

- package-lock.json
- package.json
- src/components/AppShell.tsx
- src/components/SyncTabs.tsx
- src/store/persist/db.ts
- src/store/persist/migrations.ts
- use dexie observable to store timestamps everytime the cache changes
- when a user leaves and comes back to a tab, check if there have been changes via the timestamp and reload the page if there were changes.  
- reload the page to /networks/ if the current network was not found in workspace after switching tabs
> Basic syncing tabs functionality

- src/components/ToolBar/DataMenu/LoadFromNdexDialog.tsx
- stop event from propogating in the keydown press handler that propogated the events back up to the dropdown/other parent components
> fix issue where certain keys would unfocus the search ndex bar

- src/store/hooks/useWorkspaceManager.ts
Listen to current network id changes and update the active network view accordingly.
> fix bug where active network view would persist across current network id changes

- src/models/NetworkModel/impl/CyNetwork.ts
This updates the `cytoscape` import to use the default exports of the `cytoscape` package.
It was only luck that it worked before.
Before (bad):
```
import * as cytoscape from 'cytoscape'
```
After (good):
```
import cytoscape from 'cytoscape'
```
See https://github.com/cytoscape/cytoscape.js/issues/3217#issuecomment-1981627469
@GAOChengzhan @d2fong @keiono
> Update cytoscape import

- src/components/FloatingToolBar/FloatingToolBar.tsx
- src/components/FloatingToolBar/OpenInCytoscapeButton.tsx
- src/features/HierarchyViewer/components/SubNetworkPanel.tsx
In hierarchy viewer mode, "Open in Cytoscape" button will open the active network, instead of main network.
> CW-164: unregistered networks can be opened in the Cytoscape Desktop

- src/components/NetworkPanel/CyjsRenderer/CyjsRenderer.tsx
- src/components/ToolBar/DataMenu/UploadNetworkMenuItem.tsx
- src/components/Workspace/WorkspaceEditor.tsx
- src/features/HierarchyViewer/components/SubNetworkPanel.tsx
- src/store/NetworkStore.ts
- src/store/TableStore.ts
- src/store/ViewModelStore.ts
- src/store/VisualStyleStore.ts
- src/utils/cx-utils.ts
The new data objects (networks, tables, VS, and network views) should be added only from the data store's "add" method. In this version, I removed the scattered putXtoDB methods and moved those to the store.
> Changed the code to call add to DB function only from the stores

- src/components/Vizmapper/Forms/BypassForm.tsx
- when a user selects nodes/edges, filter bypasses by the selected nodes/edges.
- when there are no selected nodes/edges, check the whole bypass map for values to display
- i.e. make the bypass form function like cytoscape desktop
> bypass form tied to selected elements

- src/components/ToolBar/ToolBar.tsx
- src/features/TableDataLoader/components/CreateNetworkFromTable/ImportNetworkFromTableMenuItem.tsx
- src/features/TableDataLoader/components/JoinTableToNetwork/JoinTableToNetworkMenuItem.tsx
- hide the help menu until proper content is available
- close the data menu after the user opens the table data loader forms
> misc menu changes

- src/models/TableModel/impl/InMemoryTable.ts
- sometimes nodes may be in the nodes aspect but not in the node attr aspect
- initialze all nodes into the node table when converting cx
> ensure all nodes are initialized in the node table

- src/components/ToolBar/DataMenu/LoadFromNdexDialog.tsx
- grey out the network summary in the ndex modal if it is a collection
- a network summary is a collection if the subnetworkIds field is a non empty list
> dont allow a user to open a collection from ndex

- src/components/TableBrowser/TableBrowser.tsx
- this will let the user know when they reached the end of their table data
> reduce overscroll x and y in the table browser

- src/components/Util/ConfirmationDialog.tsx
Ticket: [CW-242](https://cytoscape.atlassian.net/browse/CW-242)
The root of the bug is that the click on the delete icon or the confirmation window would also further trigger the click on the network panel. This can be resolved by adding e.stopPropagation() to stop the event propagation.
Previously e.stopPropagation was only added to the delete icon. After adding the confirmation window, the click on the confirmation window (either _confirm_ or _cancel_) would also trigger the click on the network panel and further set the currentNetwork ID. 
[CW-242]: https://cytoscape.atlassian.net/browse/CW-242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Solved the CW-242 bug

- src/models/VisualStyleModel/impl/MapperFactory.ts
- There exists a set of visual property values that are considered enums (node shape, edge line, visibility etc)
- All the current enum types except visibility are strings (visibility is a boolean)
- There is variation in how a user wants to passthrough map visibility:
- 'TRUE', 'True', 'false', false 
This fixes a bug in the code that assumed that visibility would always be passed as a string (sometimes people pass a boolean column)
Just looking for comments to see if this is ok.  
There is another related bug to fix that stops the flickering from happening when each passthrough value throws an error.  Or whenever multiple values throw the same error again and again.
It may be more proper to not consider visibility as an enum type and then just have specific logic for visibility to be …
> potential fix for the passthrough mapping flashing crash bug

- src/components/ToolBar/DataMenu/LoadFromNdexDialog.tsx
Add event handler in the parent modal element to prevent event propagation and prevent default.  When the user would click on the input it would trigger the menu items event handlers, overriding the input field event handler, preventing it from being focused.
> fix bug where the search ndex input could not be focused

- src/components/SummaryPanel/Summaries.tsx
- src/components/Workspace/NetworkBrowserPanel/NetworkBrowserPanel.tsx
- src/features/LLMQuery/components/LLMQueryResultPanel.tsx
Jira: [CW-234](https://cytoscape.atlassian.net/browse/CW-234)
|  Workspace |  LLM Query |
| -| -|
|<img height="350" alt="image" src="https://github.com/cytoscape/cytoscape-web/assets/39005000/f1a7eb51-7ea7-4e1f-90fe-230fd0b59773">| <img height="350" alt="image" src="https://github.com/cytoscape/cytoscape-web/assets/39005000/141de0ea-fedb-4ea9-89d0-fc40be3caea6">|
[CW-234]: https://cytoscape.atlassian.net/browse/CW-234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Make the Worksapce and LLM Query Tab stick to the top

- src/models/VisualStyleModel/impl/MapperFactory.ts
- src/models/VisualStyleModel/impl/MappingFunctionImpl.ts
- fix issue where users would passthrough map a boolean onto visibility (which is currently an enum of two string values) by converting booleans to their respective values (true => 'element', false => 'none')
- fix issue where passthrough mappings would not be populated correctly in the mapping form
> Fix passthrough bugs

- src/components/SummaryPanel/NetworkPropertyPanel.tsx
- src/components/Util/ConfirmationDialog.tsx
If the user wants to delete a network that is not the currently selected network:
1. Firstly, it would set currentNetworkId in the workspace to the networkId to delete, so that the user knows what exactly the network he/she is going to delete.
2. Then it shows the confirmation window. If the user confirms, it will delete the network from the workspace and then set the currenNetworkId in the workspace back to the network just now opened.
> Improved the behavior of delete button

- src/components/LayoutTools/Scaling.tsx
Fixes inconsistent position problems by resetting those whenever external functions updates node positions.
> Original positions will be reset when external functions updates those

- src/features/TableDataLoader/components/CreateNetworkFromTable/TableColumnAssignmentForm.tsx
- src/features/TableDataLoader/components/JoinTableToNetwork/TableColumnAppendForm.tsx
- the `delay` option was causing problems and the scroll position would keep resetting when the user scrolls
- the `height` option would conflict with the `scrollHeight` option
> fix issue where the user couldnt fully scroll to the bottom of the table data when importing tables/networks from csv files

- src/components/ToolBar/ToolsMenu/MergeNetwork.tsx
- src/features/MergeNetworks/components/MatchingTableComp.tsx
- src/features/MergeNetworks/components/MergeDialog.css
- src/features/MergeNetworks/components/MergeDialog.tsx
- src/features/MergeNetworks/components/NetAttDropDownTemplate.tsx
- src/features/MergeNetworks/models/Impl/CreateMergedNetworkWithView.ts
- src/features/MergeNetworks/models/Impl/MatchingTableImpl.ts
- src/features/MergeNetworks/store/edgeMatchingTableStore.ts
- src/features/MergeNetworks/store/mergeToolTip.ts
- src/features/MergeNetworks/store/netMatchingTableStore.ts
- src/features/MergeNetworks/store/nodeMatchingTableStore.ts
- src/features/MergeNetworks/utils/attributes-operations.ts
- src/features/MergeNetworks/utils/helper-functions.ts
- src/utils/network-utils.ts
1. In the finding unique name function, when a network name already exists in the workspace, append “_n” to the name instead of “n”.  When a user does change the name to a duplicate name, change the text color to orange and add a message explaining the reason.  
2. In the default setting, name the new attribute “Matching.Attribute”  and rename the existing “Matching.Attribute” to “Matching.Attribute_n” if there is already one exists. Add checkers for duplicate attribute names. If the duplicates are detected, change the text to red and having a red error message somewhere in that dialog box.
3. When an error is detected, grey out the merge button and display the reason in the tooltip instead of popup an error message after the user clicks the merge button. 
4. Make the header of the 2 …
> Solved A few issues in Network Merger

- src/features/HierarchyViewer/components/CustomLayout/CirclePackingPanel.tsx
- src/features/HierarchyViewer/components/CustomLayout/DataBuilderUtil.ts
- src/features/HierarchyViewer/components/MainPanel.tsx
There are some duplicate branches in the Circle Packing View. In the original version, only the original one will be highlighted when selecting subsystem in multiple locations in the hierarchy. This version selects both and display interaction network for the original branch.
> Duplicate branch handler for Circle Packing

- src/features/MergeNetworks/components/MergeDialog.tsx
- src/features/MergeNetworks/models/Impl/CreateMergedNetworkWithView.ts
- src/features/MergeNetworks/models/Impl/DifferenceMerge.ts
- src/features/MergeNetworks/tests/differenceMerge.spec.ts
- src/features/MergeNetworks/utils/helper-functions.ts
1. Implemented the 'Merge Nodes/Edges in the same network' function for difference merge
2. Added a unit test for difference merge
3. Solved a small bug when applying layout after creating a new merged network: before the network was initially set as `hasLayout:true`, this will cause error if the user interrupt the process of applying layout. Now it is initially set as `hasLayout:false` and update it as `hasLayout:true` only after successful application of layout.
> Merge Nodes/Edges in the same network (Difference merge)

- src/components/Workspace/WorkspaceEditor.tsx
Show only the first three networks if the number of networks that it fails to load is large.
> Improve the warning message

- src/components/AppShell.tsx
- src/models/CxModel/fetch-url-cx-util.ts
- In the AppShell component, after the redirect logic runs:
- Get the search parameters to see if there is a `import` key
- Get the value of the `import` key and fetch the cx, convert the cx to cyweb models
- Delete the `import` key so that the user doesnt run into the issue of importing the cx multiple times if they wanted to refresh the app
> add basic functionality to import networks from cx2 by url

- src/App.tsx
- src/Error.tsx
- src/components/AppShell.tsx
- src/features/HierarchyViewer/components/CustomLayout/CirclePackingLayout.ts
- src/features/HierarchyViewer/components/CustomLayout/CirclePackingPanel.tsx
- webpack.config.js
When uncaught errors happen and it triggers infinite loop, it forces to redirect to the top error page and stop repeating the reload.
Usually this is a fatal data loss, but necessary to reset the state.
> Force to redirect to error page and this avoids infinite loop

- src/App.tsx
- src/ErrorBoundary.tsx
- src/components/AppShell.tsx
- src/components/Workspace/WorkspaceEditor.tsx
- src/features/HierarchyViewer/components/CustomLayout/CirclePackingLayout.ts
- src/features/HierarchyViewer/components/CustomLayout/CirclePackingPanel.tsx
- src/features/HierarchyViewer/components/CustomLayout/DataBuilderUtil.ts
- src/index.tsx
This resolves the infinite loop problem and issues in tree data generation.
In some cases, the DAG to tree function generates duplicate node IDs and now it is resolved by adding "d" as suffix for duplicate nodes.
> Infinite loop issue and Duplicate node ID problem in DAG-to-Tree function

- src/components/ToolBar/DataMenu/LoadWorkspaceDialog.tsx
- src/components/ToolBar/DataMenu/SaveWorkspaceToNDExOverwrite.tsx
- src/components/ToolBar/DataMenu/index.tsx
- src/features/MergeNetworks/components/MergeDialog.tsx
- src/features/MergeNetworks/models/Impl/CreateMergedNetworkWithView.ts
- src/features/MergeNetworks/models/Impl/DifferenceMerge.ts
- src/features/MergeNetworks/tests/differenceMerge.spec.ts
- src/features/MergeNetworks/utils/helper-functions.ts
Jira: [CW-269](https://cytoscape.atlassian.net/browse/CW-269)
1. Corrected the condition of open dialog should depend on the variable **openDialog** instead of **open**. 
2. Only when the dialog is open then operate the function **fetchMyWorkspaces**. Otherwise, this function would be operated as long as the menu is open
3. Swapped the two templates, they seem to be reversed according to their naming.
(Please only focus on the updates under _src/components/Toolbar/DataMenu_, other updates are synced from other PR)
[CW-269]: https://cytoscape.atlassian.net/browse/CW-269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Solved CW-269

- src/features/HierarchyViewer/components/CustomLayout/CirclePackingPanel.tsx
Gene selection in circle packing (red circle) was not cleared after changing the selected subsystem. This fixes the issue.
> Clear leaf selection function call added when switching the subsystem

- src/models/CxModel/fetch-url-cx-util.ts
When generating the network summary for a imported cx network via url, check the resulting nodeviews to see if any of the nodes have a non zero non undefined position.  If at least one node has a non zero non undefined position, set the `hasLayout` field to true, preventing a default layout being run after loading the network.
> fix bug where importing a cx network from url would not preserve the layout

- src/components/NetworkPanel/CyjsRenderer/CyjsRenderer.tsx
- src/components/ToolBar/DataMenu/ExportNetworkToImage/PdfExportForm.tsx
- src/components/ToolBar/DataMenu/ExportNetworkToImage/PngExportForm.tsx
- src/components/ToolBar/DataMenu/ExportNetworkToImage/SvgExportForm.tsx
- src/store/RendererFunctionStore.ts
- use targetnetwork id to determine which network to export
- store renderer functions optionally by network id, use network id in conjunction with renderer and function name lookup
> fix issue where the incorrect network would be exported to an image

- src/components/Vizmapper/index.tsx
- src/models/VisualStyleModel/VisualProperty.ts
- src/models/VisualStyleModel/impl/DefaultVisualStyle.ts
- Node "Border Line" to "Border Line Type"
- "Max Edge/Node Label Width" -> "Label Width" (with mouse over "The maximum width of the node label")
- Edge Line Color -> "Stroke Color"
> Rename som visual property names in vizmapper (CW-296)

- src/components/Vizmapper/VisualPropertyRender/EdgeArrowShape.tsx
- src/components/Vizmapper/VisualPropertyRender/EdgeLine.tsx
- src/components/Vizmapper/VisualPropertyRender/Font.tsx
- src/components/Vizmapper/VisualPropertyRender/NodeBorderLine.tsx
- src/components/Vizmapper/VisualPropertyRender/NodeShape.tsx
- src/components/Vizmapper/VisualPropertyRender/Visibility.tsx
- src/components/Vizmapper/VisualStyleIcons.tsx
Sort the enum items in the popup windows of vizmapper in **alphabetical** order, and **bold** the item if it is selected.
- Node Border Line Type
- Node Shape
- Edge Line Type
- Source/Target arrow shape
- Visibility
- Font
Examples:
|Name|Display|
| -------- | ------- |
|Node Border/Edge Line Type|<img width="381" alt="image" src="https://github.com/user-attachments/assets/cae59731-7fef-4732-b63d-53647f7abaef">|
|Node Shape| <img width="446" alt="image" src="https://github.com/user-attachments/assets/536e2fbf-1135-41ac-8053-cfa4075a364c">|
|Source/Target arrow shape|<img width="575" alt="image" src="https://github.com/user-attachments/assets/1c2095da-97fb-419b-a3bb-24f397cfbe24">|
|Visibility|<img width="200" alt="image" src="https://github.com/user-attachments/assets/61084fc3-b3d1-480b-8 …
> Sort enum values in alphabetical order in Vizmapper UI and bold text when it is selected.

- src/components/Vizmapper/Forms/VisualPropertyValueForm.tsx
- src/components/Vizmapper/VisualPropertyRender/Color.tsx
- Removed the scrollbar in the color picker
- Removed some redundant code
| Tab | Display|
|------|------|
|Sequential|<img width="900" alt="image" src="https://github.com/user-attachments/assets/8199712d-bdbd-454a-ab48-8ba5bcd05895">|
|Diverging|<img width="900" alt="image" src="https://github.com/user-attachments/assets/88e0e8e5-3c62-44e7-8d04-f38c619c2f28">|
|Viridis|<img width="900" alt="image" src="https://github.com/user-attachments/assets/b0b633a5-69a6-479f-8dd6-1fb07f839329">|
|Swatches|<img width="900" alt="image" src="https://github.com/user-attachments/assets/bd1e4a57-2170-496c-ab3b-896944b49e4f">|
|Color picker|<img width="900" alt="image" src="https://github.com/user-attachments/assets/d920e8ca-1e46-456b-a67a-d94277231eb3">|
> Adjust color picker window height to avoid the vertical scrollbar 

- package-lock.json
- package.json
- src/assets/config.json
- src/components/NetworkPanel/CyjsRenderer/cyjs-factory.ts
- src/components/NetworkPanel/CyjsRenderer/cyjs-util.ts
- src/components/ToolBar/FileUpload.tsx
- src/models/VisualStyleModel/VisualPropertyValue/NodeShapeType.ts
- src/models/VisualStyleModel/impl/cxVisualPropertyConverter.ts
Jira: [CW-302](https://cytoscape.atlassian.net/browse/CW-302)
`Parallelogram` does not in exist _cytoscape.js_. Instead, it only exists `rhomboid` in _cytoscape.js_.  Therefore, I updated the convertor so that both 'parallelogram' and 'rhomboid' in cx2 are mapped to 'rhomboid' and it can be rendered correctly.
[CW-302]: https://cytoscape.atlassian.net/browse/CW-302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> translate nodeshape

- src/components/NetworkPanel/CyjsRenderer/cyjs-factory.ts
- src/components/NetworkPanel/CyjsRenderer/cyjs-util.ts
1. Solved the bug: [Cytoscape uses Degree Measure while Cytoscape-web uses Radian Measure](https://cytoscape.atlassian.net/browse/CW-304)
2. Improve the code readability and efficiency by replacing **if - else if - else** structure with a map of handler functions.
> Sovled the bug: mismatch of degree and radian measure in Cy-web and cytoscape.js

- src/components/ToolBar/FileUpload.tsx
Derive node and edge counts from the generated network model instead of extracting them from the cx metadata when a network is loaded from a cx file
> derive node and edge counts from the model when loading cx networks from file

- src/components/NetworkPanel/CyjsRenderer/CyjsRenderer.tsx
- add additive/subtractive selection when the user holds down a modified key (cmd/ctrl/shift)
- fix various bugs related to tap events in cyJsRenderer.  
- The `renderNetwork` function was accessing state like `networkView` from outside the hook.  Those values would not be up to date and the render function would be rendering the wrong values.  Updated the `renderNetwork` hooks dependencies and changed the hook to call `renderNetwork` with them.
This fixes bugs such as:
- clicking the network after loading would render the wrong visibility values for nodes/edges 
- clicking the subnetwork edge causes all the edges to disappear
> Fix selection bugs

- src/components/Vizmapper/Forms/BypassForm.tsx
- src/components/Vizmapper/index.tsx
- src/models/VisualStyleModel/impl/compute-view-util.ts
The bypass form targets two use cases:
It is assumed in this case the user wants to check the which elements have bypass on them.
If there is not one single element has bypass for this visual property, then the following window will show to remind user to select some elements to set bypass
If there exists element(s) that have bypass on them, then show it to the user( the detailed table component is **EXPANDED automatically**). The element(s) would also be SELECTED automatically.
It is assumed that in this case the user wants to directly set bypass for ALL the elements he/she has selected. Therefore, the detailed table is **automatically COLLAPSED**). However, if the user wants to set different values for different elements, then he/she has to manually click the dropdown button.
Since the …
> Bypass Form Debug and UI Adjustment 

- src/components/Vizmapper/Forms/BypassForm.tsx
- src/models/VisualStyleModel/impl/DefaultVisualStyle.ts
Jira Ticket: [CW-319](https://cytoscape.atlassian.net/browse/CW-319) 
- Corrected the typo in `DefaultVisualStyle`. It should be edgeZOrder instead of nodeZOrder.
Additional change on [Bypass Form UI Adjustment, CW-306](https://github.com/cytoscape/cytoscape-web/pull/265)
In the bypass table, empty strings are sorted to the end (instead of  to the top)after sorting alphabetically, which makes it more user-friendly:
|Before|After|
|-|-|
|<img width="400" alt="image" src="https://github.com/user-attachments/assets/c3bf9e0c-880c-4995-b7ff-0b48fa5228c4">|<img width="400" alt="image" src="https://github.com/user-attachments/assets/e924466b-e1f3-492a-b915-bde2312db999">|
[CW-319]: https://cytoscape.atlassian.net/browse/CW-319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoi …
> Solved bug of Edge Z-Order

- src/components/TableBrowser/TableBrowser.tsx
- src/components/Vizmapper/Forms/BypassForm.tsx
Immediately apply the bypass value as long as the user inputs the bypass value (get rid of the 'Apply to all selected' button')
If no network is selected, then gray out the icons in table browser toolbar to avoid triggering bugs.
> Immediately apply the Bypass Value and Table Browser Toolbar Debug

- src/components/NetworkPanel/CyjsRenderer/CyjsRenderer.tsx
If the user selects one or some node-type element(s), the user has to select edge-type elements by keeping pressing 'Shift' or 'command'. Otherwise, the nodes would be deselected and the newly clicked edge would be selected. 
And verse vice.
> Deselect the other element type when the element selection type changes

- src/models/VisualStyleModel/impl/MapperFactory.ts
- In the previous version, the mapping function would blindly do the mapping whether the attribute value is out of the domain or not.
- Now, the refined version would detect the attribute value and if it is out the defined domain, then apply the max/min vp value.
> Set max and min for continuous mapping

- src/models/VisualStyleModel/impl/MapperFactory.ts
Now cytoscape-web could read the customized settings for out-of-bound values in continuous mapping.
> Render customized min/max value

- src/components/TableBrowser/TableBrowser.tsx
- src/components/ToolBar/DataMenu/ExportNetworkToImage/ExportNetworkToImageMenuItem.tsx
- src/components/ToolBar/DataMenu/ExportNetworkToImage/PdfExportForm.tsx
- src/components/ToolBar/DataMenu/ExportNetworkToImage/PngExportForm.tsx
- src/components/ToolBar/DataMenu/ExportNetworkToImage/SvgExportForm.tsx
Jira: [CW-341](https://cytoscape.atlassian.net/browse/CW-341)
The previous version would prevent users from clicking the tab. The adjustment makes it smoother to switch from icons to tabs or other buttons.
|||
|-----|-----|
|Now|<img width="793" alt="image" src="https://github.com/user-attachments/assets/14edbaa4-6d41-48cc-aa1d-e97fd66aa55e">|
|Before|<img width="793" alt="image" src="https://github.com/user-attachments/assets/45292708-57a4-403d-8c9b-6970e6f0da67">|
[CW-341]: https://cytoscape.atlassian.net/browse/CW-341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Adjustment on the Postion of Table Browser Icons' Tooltip 

- src/components/Workspace/WorkspaceEditor.tsx
The default height is now 20% of the viewport (window)
> Table browser's default height will be calculated based on the window size

- index.html
> removed 2.0 from title of app. Fix for CW-368

- src/features/HierarchyViewer/components/MainPanel.tsx
- src/features/HierarchyViewer/store/useHierarchyViewerManager.tsx
- src/features/HierarchyViewer/utils/hierarchy-util.ts
This fixes the problem of showing unnecessary CP view panel tab. The renderer will be removed in the manager, so even if the panel is closed it hides the CP tab correctly.
> CP renderer will be deleted in the manager instead of the panel

- src/components/ToolBar/DataMenu/SaveToNDExMenuItem.tsx
- src/models/NetworkModel/AccessPermission.ts
Ticket: [CW-125](https://cytoscape.atlassian.net/browse/CW-125)
To determine whether to enable 'Save to NDEx (update)' or not, it will check mainly three aspects:
[CW-125]: https://cytoscape.atlassian.net/browse/CW-125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Checked Availibility of Save to NDEx button

- src/components/ToolBar/AppMenu/menu-factory.tsx
This adds a tooltip when a user hovers over an input column dropdown for service based apps
> Wrapped Input Column parameter with tooltip. Fix for CW-381

- package-lock.json
- src/components/NetworkPanel/CyjsRenderer/CyjsRenderer.tsx
- src/components/ToolBar/DataMenu/ExportNetworkToImage/SvgExportForm.tsx
Fixes an issue where clicking the export full network as image checkbox would not work.
> Fix full option in the export svg form

- src/components/TableBrowser/TableBrowser.tsx
- src/components/Workspace/WorkspaceEditor.tsx
Jira Ticket:  [CW-383](https://cytoscape.atlassian.net/browse/CW-383)
It seems that previously the indicator, `currentNetworkIsNotModified`, is not determinated correctly. Now I changed it to only check whether the flag `isModified` of the current network is `undefined` or `false`:
- `undefined`: never touched by the code, the network has never been updated since it was loaded to website
- `false`: the network has been changed, but it was successfully saved to NDEx and the flag of `isModified` is set to false again by the menu item: Save the Current Network to NDEx
[CW-383]: https://cytoscape.atlassian.net/browse/CW-383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolved isModified flag Bug

- src/features/LLMQuery/components/LLMQueryOptionsMenuItem.tsx
- src/features/LLMQuery/model/LLMTemplate.ts
Fix fo CW-365, just replaced template with prompt in UI components. Left internal object names the same.
> Change label from template to prompt for LLM analysis

- src/components/ToolBar/DataMenu/ExportNetworkToImage/PngExportForm.tsx
- fix issue where DPI label would not be displayed properly
- fix issues in the png export form where height/width/inches/zoom would not sync together when either of these values were edited.
To test it out, open any network in cyweb, open the png export form, then play around with the height/width/inches/zoom values.  They should all sync when one field is changed.
> Image export tweaks

- src/utils/is-url.ts
- Update the isValidUrl function with a regex that filters for values like `test.com` `http://test.com` `https://test.com` `www.test.com`, while rejecting values like `protein`, `hgnc.symbol:TLR10, hgnc.symbol:TLR8, hgnc.symbol:TLR7, hgnc.symbol:TLR6, hgnc.symbol:TLR1, hgnc.symbol:TLR9, hgnc.symbol:TLR2, hgnc.symbol:TLR5, hgnc.symbol:TLR4, hgnc.symbol:TLR3`, `signor:SIGNOR-C124`.
To test, edit any table browser cell in any network and paste these values in.  Only the first set of values should be displayed as a clickable URL.  The other values should be rendered regular strings.
> Fix issue where certain strings would be rendered as clickable URLs

- src/features/MergeNetworks/components/MergeDialog.tsx
- src/features/MergeNetworks/models/Impl/DifferenceMerge.ts
This resolution can solve these two bugs: [CW-393](https://cytoscape.atlassian.net/browse/CW-393) and [CW-394](https://cytoscape.atlassian.net/browse/CW-394).
It turns out the checkbox, ratio buttons and text input cannot behave properly because of a focus-related bug(When showing the dialog, the focus should be on the dialog instead of other components). This can be resolved by adding `stopPropagation` to the dialog component:
```
onKeyDown={(e) => {
e.stopPropagation()
}}
onClick={(e) => {
e.stopPropagation()
}}
```
[CW-393]: https://cytoscape.atlassian.net/browse/CW-393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CW-394]: https://cytoscape.atlassian.net/browse/CW-394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ …
> Resolved Focus-related Bugs in Merge Dialog

- src/features/MergeNetworks/components/MergeDialog.tsx
Solved two tickets:
- [CW-396](https://cytoscape.atlassian.net/browse/CW-396): Add tooltip for three merge types
- [CW-399](https://cytoscape.atlassian.net/browse/CW-399): Move network naming out of  the Advanced Options
[CW-396]: https://cytoscape.atlassian.net/browse/CW-396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CW-399]: https://cytoscape.atlassian.net/browse/CW-399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add tooltip for the merge types and move network naming out of 'advanced options'

- src/components/AppManager/ServiceSettingsDialog.tsx
- src/store/AppStore.ts
- src/utils/service-fetcher.ts
Ticket: [CW-401](https://cytoscape.atlassian.net/browse/CW-401)
Move the try-catch block to the earliest function in the call chain instead of an intermediate function. Added the following code to check whether the metadata is fetched successfully; otherwise, the try-catch block may be bypassed, even if the fetch fails.
```
if (!response.ok) {
throw new Error("Failed to fetch the service metadata.")
}
```
[CW-401]: https://cytoscape.atlassian.net/browse/CW-401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Check Adding Service

- src/components/Vizmapper/index.tsx
In the previous version, the entire row would trigger the tooltip. If the tooltip was active and the user clicked the mapping/bypass button (keeping the tooltip in its active state), it could lead to the following issues:
- Bug 1: The tooltip is above the dialog.
- Bug 2: Even if the mouse moved elsewhere (e.g., over the network panel, where the tooltip would theoretically close), the tooltip would persist, failing to close as expected.
After discussing with Jing, a simple and effective solution is to restrict the tooltip trigger to the text within the row, rather than the entire row.
> Bug of Tooltips in vizmapper

- src/components/Workspace/WorkspaceEditor.tsx
- src/models/OpaqueAspectModel/OpaqueAspects.ts
- src/models/OpaqueAspectModel/index.ts
- src/models/StoreModel/OpaqueAspectStoreModel.ts
- src/store/OpaqueAspectStore.ts
- src/store/hooks/useNdexNetwork.ts
- src/store/hooks/useWorkspaceManager.ts
- src/store/persist/db.ts
- src/utils/CachedData.ts
The CX2 reader now register optional opaque aspects to its data store. It can be accessible via _useOpaqueAspectsStore_.
Also, this change includes a new entry in the DB schema, and its version has been updated to v4.
> New Opaque Aspect store

- src/components/ToolBar/LayoutMenu/LayoutOptionDialog.tsx
- src/components/ToolBar/LayoutMenu/index.tsx
- src/features/LLMQuery/components/RunLLMQueryMenuItem.tsx
Jira Ticket: [CW-413](https://cytoscape.atlassian.net/browse/CW-413)
- Disable the layout menu items when the workspace is empty
- Always enable the root menu button and only disable the layout menu items when necessary (users can have access to the layout settings)
[CW-413]: https://cytoscape.atlassian.net/browse/CW-413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Disable the layout menu items when the workspace is empty

- src/components/NetworkPanel/NetworkTabs.tsx
- src/features/HierarchyViewer/components/MainPanel.tsx
- src/models/StoreModel/UiStateStoreModel.ts
- src/models/UiModel/Ui.ts
- src/store/UiStateStore.ts
When multiple views are available, the developers can set custom tab name if they need. For now, it is used by the hierarchy viewer and it sets network tab name to "Tree View."
> New UI state for custom tab name has been added.

- src/components/Vizmapper/Forms/MappingForm/ContinuousMappingForm/ColorGradient.tsx
- src/components/Vizmapper/Forms/MappingForm/ContinuousMappingForm/ContinuousColorMappingForm.tsx
- src/components/Vizmapper/Forms/MappingForm/ContinuousMappingForm/ContinuousNumberMappingForm.tsx
- src/components/Vizmapper/Forms/MappingForm/ContinuousMappingForm/ExpandableNumberInput.tsx
- src/models/StoreModel/VisualStyleStoreModel.ts
- src/models/VisualStyleModel/VisualMappingFunction/ContinuousMappingFunction.ts
- src/models/VisualStyleModel/impl/MapperFactory.ts
- src/models/VisualStyleModel/impl/VisualStyleFnImpl.ts
- src/models/VisualStyleModel/impl/cxVisualPropertyConverter.ts
- src/store/VisualStyleStore.ts
- src/utils/is-url.ts
- Continuous number mapper uses ExpandableNumberInput instead of TextFields, allowing users to cancel/confirm new number values alongside min/max validation
- Various style tweaks for the color mapper and number mapper dialog.
- Fix issue where users could enter values greater than the min/max for any handle and in the new handle form.
- Change all number inputs in the continous color mapper to have cancel/confirm behaviour.  The mapping will not be updated until the user presses confirm.
- Fix issue where negative numbers and decimals couldn't be entered into the number inputs.
- Use the same render function for the color gradient in the continuous mapping form as the one that is used for color rendering in the network view.
- Users can click anywhere on any handle to bring it to the …
> Continuous mapping values fix

- src/components/Vizmapper/Forms/MappingForm/DiscreteMappingForm.tsx
- src/components/Vizmapper/Forms/MappingForm/index.tsx
Ticket: [CW-406](https://cytoscape.atlassian.net/browse/CW-406)
- Adjust paddings/margins in the dialog form
- Adjust the dialog size to keep consistent with the Bypass Form
- Remove the extra paddings in the table cells
- Reposition the dialog more reasonably when mapping type changes
- Adjust the tooltip:
- Make the items' tooltip in the dropdown lists to the right side so that they would not block users from choosing other items if they trigger the tooltips
- In the table cells, only hovering the warning icon can trigger the tooltip.
[CW-406]: https://cytoscape.atlassian.net/browse/CW-406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Mapping Form UI Improvement

- src/components/TableBrowser/TableBrowser.tsx
- src/components/Vizmapper/VisualPropertyRender/Checkbox.tsx
- src/components/Workspace/WorkspaceEditor.tsx
Ticket: [https://cytoscape.atlassian.net/browse/CW-418](https://cytoscape.atlassian.net/browse/CW-418)
Mark network as isModified when these properties change:
- VisualStyle
- VisualStyleOptions (only includes status of _nodeSizeLocked_ and _arrowColorMatchesEdge_ for now)
> Mark network as modified if style changes

- src/features/HierarchyViewer/components/MainPanel.tsx
- src/features/HierarchyViewer/store/useHierarchyViewerManager.tsx
Moved the section to update the tab name from the panel component to manager (Custom Hook) to avoid unnecessary name change caused by destroyed component.
> CW-428: Moved custom tab name manager to the custom hook from the panel

- src/components/NetworkPanel/CyjsRenderer/CyjsRenderer.tsx
- src/features/HierarchyViewer/components/SubNetworkPanel.tsx
I've tried several ideas for show/hide edge features for filtering, but it requires major change in the renderer, so for this round, I'll keep the same mechanism, but use the normal selection mode whenever filters are not available for the interaction network.
> Simple Fix for CW-376 (missing edges)

- src/components/ToolBar/BaseMenuProps.ts
- src/components/ToolBar/DataMenu/SaveWorkspaceToNDEx.tsx
- src/components/ToolBar/DataMenu/SaveWorkspaceToNDExOverwrite.tsx
- src/components/ToolBar/DataMenu/index.tsx
Solved [CW-420](https://cytoscape.atlassian.net/browse/CW-420) and [CW-422](https://cytoscape.atlassian.net/browse/CW-422)
- Updated the tooltip of two workspace menu items
- Detect workspace name duplication in advance and give users warning in the dialog
[CW-420]: https://cytoscape.atlassian.net/browse/CW-420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CW-422]: https://cytoscape.atlassian.net/browse/CW-422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Debug and Improvements on Workspace Menu Item

- src/components/ToolBar/DataMenu/DownloadNetworkMenuItem.tsx
- src/models/TableModel/impl/ValueTypeImpl.ts
- src/store/hooks/useNdexNetworkSummary.ts
- src/store/io/exportCX.ts
This commit can resolve two bugs: [CW-425](https://cytoscape.atlassian.net/browse/CW-425) and [CW-426](https://cytoscape.atlassian.net/browse/CW-426)
- Added a post-process function for the summary fetcher: the current fetcher function convert all data types of the summary properties to `string` type, here a post-process function is added to parse the value. (In the future this function will upgraded to V3 and would not have this problem any more.)
- Added a try-catch block for downloading the network and added message to notify the results of the download.
- During exportation to Cx2 files, only call `deserializeValue` function when necessary
[CW-425]: https://cytoscape.atlassian.net/browse/CW-425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
> File download debug and array data parse in summary property

- src/models/VisualStyleModel/impl/VisualStyleFnImpl.ts
- This led to an issue where exporting networks to CX would be invalid because the edge ids would not match the edge bypass ids.
To test:
- load the attached network in ticket CW-433 into cytoscape web
- sign in to ndex and save the network to ndex
- the network should be valid according to the ndex webapp and viewable in the network-viewer
> Fix issue where edge bypasses were not translated from CX correctly

- src/components/FloatingToolBar/FitButton.tsx
- src/components/FloatingToolBar/FloatingToolBar.tsx
- src/components/FloatingToolBar/OpenInCytoscapeButton.tsx
- src/components/FloatingToolBar/ShareNetworkButtton.tsx
Jira: [CW-438](https://cytoscape.atlassian.net/browse/CW-438)
For an HCX network, when the active network is the main network, and the user clicks the floating toolbar in the subnetwork renderer, it will trigger the action first and then set the subnetwork as the active network view. Therefore, it still uses out-of-date `activaNetworkView` for the action.
The bug is resolved by sending the bonded networkId to the floating toolbar to avoid using `activaNetworkView`.
[CW-438]: https://cytoscape.atlassian.net/browse/CW-438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix floating toolbar bug

- src/components/Messages/SnackbarMessageList.tsx
- src/components/ToolBar/FileUpload.tsx
- src/features/TableDataLoader/components/JoinTableToNetwork/TableUpload.tsx
- Fix issue where the display message would not show when an unsupported file type is uploaded.
Testing:
1. Upload any file type that is not supported
2. A message should show saying the file is not supported
3. The app should not crash
> Fix issue where uploading an unsupported file type crashes the app

- src/components/ToolBar/DataMenu/index.tsx
- src/components/ToolBar/DataMenu/menuItem.css
Ticket: [CW-403](https://cytoscape.atlassian.net/browse/CW-403)
- Make nested menu item have the same height as other menu items
- Make the gray background (when hovering the button) would NOT overlap with the divider line
[CW-403]: https://cytoscape.atlassian.net/browse/CW-403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolved that menu items overlap the divider lines

- src/components/ToolBar/DataMenu/CopyNetworkToNDExMenuItem.tsx
- src/components/ToolBar/DataMenu/SaveToNDExMenuItem.tsx
- src/components/ToolBar/DataMenu/SaveWorkspaceToNDEx.tsx
- src/components/ToolBar/DataMenu/SaveWorkspaceToNDExOverwrite.tsx
- src/components/ToolBar/DataMenu/index.tsx
- src/components/ToolBar/FileUpload.tsx
- src/components/Vizmapper/Forms/MappingForm/index.tsx
- src/models/NetworkWithViewModel/NetworkWithView.ts
- src/models/StoreModel/VisualStyleStoreModel.ts
- src/models/VisualStyleModel/VisualMappingFunction/VisualMappingFunction.ts
- src/models/VisualStyleModel/impl/VisualStyleFnImpl.ts
- src/models/VisualStyleModel/impl/cxVisualPropertyConverter.ts
- src/store/io/exportCX.ts
- src/store/persist/db.ts
- src/utils/CachedData.ts
- src/utils/cx-utils.ts
- src/utils/ndex-utils.ts
The root of the error is related to two bugs:
- The generated CX2 file is illegal since the mapping's definition does not contain the attribute type information and it would be marked as illegal by NDEx. Now this is resolved by adding this entry to the CX2 file during both import and export process. (See commit [Add type to mapping definition](https://github.com/cytoscape/cytoscape-web/commit/c8c9fbbdedfef190fbe873b4136df0f38e11ac61))
- When saving a new network to NDEx, the original workflow would not check whether the network is accepted by NDEx or not. Now this is resolved by checking the summary from the newly created network in NDEx. (See commit [check whether the network is rejected by NDEx](https://github.com/cytoscape/cytoscape-web/commit/cabf4f203fee95dc899e631dd501b0ba4daede61))
> Resolved U2OS losing layout bug

- src/components/ToolBar/DataMenu/CopyNetworkToNDExMenuItem.tsx
- src/components/ToolBar/DataMenu/SaveToNDExMenuItem.tsx
- src/components/ToolBar/DataMenu/SaveWorkspaceToNDEx.tsx
- src/components/ToolBar/DataMenu/SaveWorkspaceToNDExOverwrite.tsx
- src/components/ToolBar/DataMenu/index.tsx
- src/components/ToolBar/FileUpload.tsx
- src/components/Vizmapper/Forms/MappingForm/index.tsx
- src/models/NetworkWithViewModel/NetworkWithView.ts
- src/models/StoreModel/VisualStyleStoreModel.ts
- src/models/VisualStyleModel/VisualMappingFunction/VisualMappingFunction.ts
- src/models/VisualStyleModel/impl/VisualStyleFnImpl.ts
- src/models/VisualStyleModel/impl/cxVisualPropertyConverter.ts
- src/store/OpaqueAspectStore.ts
- src/store/io/exportCX.ts
- src/store/persist/db.ts
- src/utils/CachedData.ts
- src/utils/cx-utils.ts
- src/utils/ndex-utils.ts
This PR 
- Added an NDEx summary checker after save/update the network to NDEx sothat we can ensure NDEx accepts the network (See `src/utils/ndex-utils.ts`).
- Changed the cx2 exporter:  added the **attribute type**  to the mapping's definition when the attribute does not exist in the node/edge table (See `src/store/io/exportCX.ts`).
(The above two changes resolved the [CW-437](https://cytoscape.atlassian.net/browse/CW-437) since its caused by the exported cx2 file of U2OS network is not accepted by NDEx)
- Added `getOpaqueAspect` in `getCachedData` function to resolve [CW-452](https://cytoscape.atlassian.net/browse/CW-452) (See `src/utils/cx-utils.ts`). Otherwise getting all cached data will never be fulfilled since the OpaqueAspect data is always missing. Then loading a local cx2 file …
> Fix opaque store bug & Add ndex summary checker & Improve cx2 exporter

- src/components/ToolBar/AppMenu/index.tsx
- src/components/Workspace/SidePanel/TabContents.tsx
- src/store/AppStore.ts
Now both panels and menu items will be disabled when the checkbox are unchecked.
Also, by default, apps are disabled and users need to activate it if they want to use it in the workspace.
> CW-463 fixed enable/disable function for Apps.

- src/components/NetworkPanel/NetworkPanel.tsx
- src/components/Workspace/WorkspaceEditor.tsx
- Add a parameter in the NetworkPanel to indicate whether the network is loaded successfully
> Notify user when it fails to load network

- src/components/Messages/SnackbarMessageList.tsx
- src/components/ToolBar/DataMenu/CopyNetworkToNDExMenuItem.tsx
- src/components/ToolBar/DataMenu/LoadWorkspaceDialog.tsx
- src/components/ToolBar/DataMenu/SaveToNDExMenuItem.tsx
- src/components/ToolBar/DataMenu/SaveWorkspaceToNDEx.tsx
- src/components/ToolBar/DataMenu/SaveWorkspaceToNDExOverwrite.tsx
- src/utils/ndex-utils.ts
This PR consists of two parts:
It is a bug that triggers a database error when loading a workspace (it will firstly clear the current workspace and then load the target workspace). 
This is resolved by a simple fix by deleting **the redundant line** in the `handleOpenWorkspace` function: 
```
deleteAllNetworks()
```
`getNDExSummaryStatus`: As required by Jing, the retry times of fetching summary info from NDEx is increased to 13 times and the intervals are adjusted accordingly.
A new special error message, `NDEx_TIMEOUT_ERROR,` is also added to denote that on the NDEx side it reaches the maximum expected time to process the network. Correspondingly, a checker for this error is added in the `try-catch` blocks of the saveNetwork functions.
In addition, message snackbar is improved so that …
> Fixed load-workspace bug & Improved getNDExSummaryStatus

- src/components/ToolBar/FileUpload.tsx
- src/models/TableModel/impl/InMemoryTable.ts
Ticket: [CW-484](https://cytoscape.atlassian.net/browse/CW-484)
Add a checker before iterate through the node attributes so that it would not cause the error if the node attribute is empty
```
const nodeAttrDefs = attrDefs.nodes
if (nodeAttrDefs !== undefined) {
Object.entries(nodeAttrDefs).forEach(([attrName, attrDef]) => {
...
})
}
```
[CW-484]: https://cytoscape.atlassian.net/browse/CW-484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Debug "failed to load network with no node and edge attributes"

- src/components/ToolBar/DataMenu/CopyNetworkToNDExMenuItem.tsx
- src/components/ToolBar/DataMenu/DownloadNetworkMenuItem.tsx
- src/components/ToolBar/DataMenu/ExportNetworkToImage/ExportNetworkToImageMenuItem.tsx
- src/components/ToolBar/DataMenu/ImportNetworkFromFileMenuItem.tsx
- src/components/ToolBar/DataMenu/LoadFromNdexDialog.tsx
- src/components/ToolBar/DataMenu/LoadFromNdexMenuItem.tsx
- src/components/ToolBar/DataMenu/LoadWorkspaceMenuItem.tsx
- src/components/ToolBar/DataMenu/OpenNetworkInCytoscapeMenuItem.tsx
- src/components/ToolBar/DataMenu/RemoveAllNetworksMenuItem.tsx
- src/components/ToolBar/DataMenu/RemoveNetworkMenuItem.tsx
- src/components/ToolBar/DataMenu/SaveToNDExMenuItem.tsx
- src/components/ToolBar/DataMenu/SaveWorkspaceToNDEx.tsx
- src/components/ToolBar/DataMenu/SaveWorkspaceToNDExOverwrite.tsx
- src/components/ToolBar/LayoutMenu/index.tsx
- src/features/TableDataLoader/components/JoinTableToNetwork/JoinTableToNetworkMenuItem.tsx
- src/utils/ndex-utils.ts
- If a menu item name ends with `...`, it means it will open a dialog.
- Get rid of some words like `current` or `network` to be more concise
- 'Open workspace' is also disabled when the user is anonymous
- Enable it to save the `local` networks (previously it could not do this)
- It will create a copy for the local network, save it to NDEx and then delete the origin one
- The behavior is similar to `Save Copy to NDEx` (previously called `Save Current Network to NDEx as...`). The only difference is that the latter would not delete the original one
- When there are local networks in the workspace, `Saving workspace` operation  (no matter creating a new workspace entry or updating an existing one) will adopt the `save copy and delete original one` strategy
|After change| Before change| …
> Improve User Experience on Data Menu

- src/components/SummaryPanel/NdexNetworkPropertyEditor.tsx
- src/components/SummaryPanel/NdexNetworkPropertyTable.tsx
- src/components/TableBrowser/NetworkInfoPanel.tsx
- Reverse the previous [fix](https://github.com/cytoscape/cytoscape-web/pull/390). It was intended to listen to the changes on the network property at one single place, but this is bound to the UI, so as long as the user does not open the 'network' panel in the bottom, it would not be triggered successfully.
-  src/components/TableBrowser/NetworkInfoPanel.tsx
- Added `setNetworkModified` after every `updateNetworkSummary` in the NdexNetworkProperty Dialog
- src/components/SummaryPanel/NdexNetworkPropertyEditor.tsx
- src/components/SummaryPanel/NdexNetworkPropertyTable.tsx
1. Choose a network that does not have the red mark. Click the 'pencil' icon to edit network properties , as shown below:
2. After the click, the dialog would show and make some changes in the dialog(update the network …
> 'Set Network isModified' Debug

- src/bootstrap.tsx
- src/components/FeatureAvailability/FeatureAvailabilityContext.ts
- src/components/FeatureAvailability/FeatureAvailabilityProvider.tsx
- src/components/FeatureAvailability/index.ts
- src/components/FloatingToolBar/OpenInCytoscapeButton.tsx
- src/components/ToolBar/DataMenu/OpenNetworkInCytoscapeMenuItem.tsx
- src/store/hooks/useOpenInCytoscapeDesktop.ts
Ticket: [CW-490](https://cytoscape.atlassian.net/browse/CW-490)
1. Open Cytoscape-Web and observe the behavior of the two "Open in Cytoscape Desktop" buttons as Cytoscape-Desktop is started or stopped.
2. Ensure that the buttons are enabled when Cytoscape-Desktop is running and disabled when it is not.
3. Click the enabled button to test whether it can open the copy of the network in the Cytoscape Desktop successfully.
One button is in `Data -> Open Network in Cytoscape` menu, the other is in the floating toolbar of the renderer.
[CW-490]: https://cytoscape.atlassian.net/browse/CW-490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add Context to check Cytoscape Desktop's availability

- src/components/Workspace/WorkspaceEditor.tsx
Ticket: [CW-483](https://cytoscape.atlassian.net/browse/CW-483)
Added a line to reset the network's **isModified** flag as `false` if the network does not have a layout and would be applied the default layout when loading
- Try to load this network (UUID: 06f859c1-8051-11ef-b4e1-005056ae6f73) 
- It will not have the 'red' mark once loaded
[CW-483]: https://cytoscape.atlassian.net/browse/CW-483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Reset isModified as false after initial layout apply

- src/components/AppManager/AppListPanel.tsx
- src/components/AppManager/ServiceListPanel.tsx
- src/features/ServiceApps/resultHandler/updateTables.ts
Ticket: [CW-498](https://cytoscape.atlassian.net/browse/CW-498) and [CW-499](https://cytoscape.atlassian.net/browse/CW-499)
- Added a check for the edge id starting with 'e', if not, then left append 'e' to the edge id
- Renamed headers as required in [CW-498](https://cytoscape.atlassian.net/browse/CW-498)
- Load a network in cytoscape web and use this service app: [updateTables](https://cd.ndexbio.org/cy/cytocontainer/v1/updatetablesexample)
- Check “Apply to edge” checkbox and click submit.
- Check whether this action can add the column and default value to all edge rows successfully
[CW-499]: https://cytoscape.atlassian.net/browse/CW-499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CW-498]: …
> Check if the edge id starts with 'e' for updateTable Action

- src/components/FloatingToolBar/ShareNetworkButtton.tsx
- src/components/ToolBar/AppMenu/menu-factory.tsx
- src/features/ServiceApps/index.ts
- src/store/hooks/useServiceTaskRunner.ts
TIcket: [CW-491](https://cytoscape.atlassian.net/browse/CW-491)
- Disable the **submit** button in the app dialog ONLY WHEN the network/table data is required in the service-app's `serviceInputDefinition`
- Customize the tooltip for two cases 
- There is no active network
- The input column does not exist in the table 
- Some code clean in `src/components/FloatingToolBar/ShareNetworkButtton.tsx`
- Add service apps in the `App -> App Manager`
- Delete all the networks in the current workspace
- Check
-  The Service-app [Open URL - null service input definition](https://cd.ndexbio.org/cy/cytocontainer/v1/openurlexamplenoinput) can be run (the submit button would be enabled)
- All other service-app cannot be run, namely the 'submit' button is disabled with different tooltips
- Apps under …
> Allow null for inputNetwork or inputColumns in serviceInputDefinition

- src/components/Vizmapper/Forms/MappingForm/ContinuousMappingForm/ContinuousColorMappingForm.tsx
- src/components/Vizmapper/Forms/MappingForm/ContinuousMappingForm/ContinuousNumberMappingForm.tsx
- Set default value of the new handle form to be the mean of the max and min values
- Users can drag the end handles along the y axis
- Fix issue where long column names would overflow the new handle form
> Fix continuous mapping form ui issues

- src/components/ToolBar/DataMenu/LoadWorkspaceDialog.tsx
https://cytoscape.atlassian.net/jira/software/projects/CW/issues/CW-482
> create a new workspace id in the local if the deleted NDEx workspace UUID is same as the local workspace UUID

- src/components/ToolBar/DataMenu/CopyNetworkToNDExMenuItem.tsx
- src/components/ToolBar/DataMenu/SaveToNDExMenuItem.tsx
- src/components/ToolBar/DataMenu/SaveWorkspaceToNDExOverwrite.tsx
- src/components/ToolBar/DataMenu/WorkspaceNamingDialog.tsx
- src/utils/ndex-utils.ts
- Added tooltips for 'Save Network' and 'Save Workspace' since they would overwrite data
|Menu Item | Scenario |Tooltip|
|-----|-----|-----|
|Save Network | Save a local network to NDEx|<img width="400" alt="image" src="https://github.com/user-attachments/assets/ccf3a795-cc39-4be3-8c23-850f6c57299d" />|
|Save Network | Save a NDEx network|<img width="400" alt="image" src="https://github.com/user-attachments/assets/70b824af-06e4-492b-8714-36480b31a8ac" />|
|Save Workspace |Create a new workspace in NDEx|<img width="400" alt="image" src="https://github.com/user-attachments/assets/c2b05635-7ed1-4507-91d5-39747d377bcd" />|
|Save Workspace |Overwrite the remote version in NDEx|<img width="400" alt="image" src="https://github.com/user-attachments/assets/be2ca86f-45f5-493d-9ef5-5e7cc47914af" />| …
> Minor improvements on 'Saving Workspace'

- src/components/AppShell.tsx
- src/models/StoreModel/MessageStoreModel.ts
- src/store/MessageStore.ts
Ticket: [possibly wrong message when opening workspace from NDEx](https://cytoscape.atlassian.net/browse/CW-519)
When loading another workspace, the message snack-bar component would be rerendered. And in that component, there is a **state**, called [currentMessageIndex](https://github.com/cytoscape/cytoscape-web/blob/development/src/components/Messages/SnackbarMessageList.tsx#L10), would be reset to 0. It controls the index of the message that would be shown in the snack-bar. Therefore, if the message list is not cleaned when redirecting the url, it would iterate through the message list again after redirect.
1. Click 'save workspace' or 'open network in Cytoscape' that would trigger the message
2. Open a workspace in your account by clicking `Data -> Open Workspace from NDEx`
3. The …
> Clear messages if the url is redirected to another workspace

- src/store/VisualStyleStore.ts
- Update the default color scheme colors to be the same ones as Cytoscape Desktop
- Set the min and max values of the continous color creation function to be the largest absolute value if the data is two tailed
- Unable to fix the selected palette as the palette UI code needs to be reworked
> Partial fix for CW-513

- src/components/ToolBar/DataMenu/SaveWorkspaceToNDExOverwrite.tsx
- src/components/ToolBar/DataMenu/WorkspaceNamingDialog.tsx
- src/store/hooks/useWorkspaceData.ts
- src/utils/ndex-utils.ts
Load the up-to-date workspace from Database when update a current workspace or create a new workspace
- Clear the current workspace by clicking `Data -> Clear Local Database`
- Import a CX2 file to the workspace
- Save the workspace and give it a name that is the same as one of your existing workspace.
- Click `overwrite` when the confirmation dialog pops up
- It will remind that: Failed to save the workspace
> Debug save local networks to workspace

- src/components/AppShell.tsx
- src/components/UpdateNetworkDialog.tsx
This is a fix for this [ticket](https://cytoscape.atlassian.net/browse/CW-516)
Set the `urlNetIdRef` value to an empty string after use in the `redirect` function.
This could resolve the bug and also would not break the original "share network logic"
- Add 'Waitsecond' before setCurrentNetworkId if the networkId is just added into the workspace
- Clear the UpdateNetwork dialog
- Delete the unnecessary code since the dialog is shown only when the user is authenticated
- Pass the correct target networkId to the dialog  instead of reading the currentNetworkId (the target networkId is not necessarily the current one)
[Fix bug of adding an extra network when loading workspace](https://github.com/cytoscape/cytoscape-web/pull/418)
[CW-516 Fixed timing issue after loading …
> Clear urlNetIdRef after use

- src/components/TableBrowser/TableBrowser.tsx
- src/components/ToolBar/AppMenu/menu-factory.tsx
- src/models/AppModel/ServiceMetadata.ts
- src/utils/is-url.ts
- src/utils/url-util.ts
Ticket: [CW-473](https://cytoscape.atlassian.net/browse/CW-473)
- Check whether there are name duplications between the existing and the newly added paths.
- If it is the end of the path (namely the last item), then it will add tooltips for them (as long as they have template and they are not intermediate menu items)
- If they are both intermediate menu items, then merge these path by letting the newly added paths follow the existing one
[CW-473]: https://cytoscape.atlassian.net/browse/CW-473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Tooltip for duplicated App Menu Items

- package-lock.json
- package.json
- src/components/NetworkPanel/CyjsRenderer/CyjsRenderer.tsx
- Depending on how the network summary is retrieved from NDEx, it may give a network attribute value as a single string even when it specifies the data type as an array
Fixes CW-508
Load network 495f1d07-eb3b-11eb-b666-0ac135e8bacf from dev1 into cytoscape web.  The annotation should be displayed.
> Fix issue where annotations may not be rendered

- src/components/TableBrowser/TableBrowser.tsx
- src/components/TableBrowser/TableColumnForm.tsx
- src/models/TableModel/impl/ValueTypeImpl.ts
- Perform a check when the user inputs values into integer columns in the table browser
- Reject the value if it is a float.
Testing:
- Open a network
- Input a decimal value in a integer column
- It should not update the value
> Fix issue where users could input floats into integer columns

- src/models/CxModel/fetch-url-cx-util.ts
Ticket: [CW-529](https://cytoscape.atlassian.net/browse/CW-529)
**Changes:**
- Fixes importing the network `description` and other network properties from a URL-fetched CX2 data.
- I'm also suggesting a better default `name`--Instead of "test", one that contains the URL host and import date/time (e.g. `iregulon.baderlab.net (3/4/2025, 4:15:08 PM)`).
____
[CW-529]: https://cytoscape.atlassian.net/browse/CW-529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Import network description/properties from URL-fetched CX2

- src/components/NetworkPanel/NetworkTabs.tsx
This pull request enhances the `NetworkTabs` component in `src/components/NetworkPanel/NetworkTabs.tsx` by adding functionality to persist the active network view tab state in the URL. This ensures that the selected tab remains consistent when the user navigates back to the page or refreshes it. The key changes include importing necessary hooks, defining a constant for the URL parameter, updating the URL when the tab changes, and reading the tab state from the URL on initial render.
Global state for selected network view is already there, and local DB is not updated.
Enhancements to `NetworkTabs` component:
* [`src/components/NetworkPanel/NetworkTabs.tsx`](diffhunk://#diff-287ffcdfc714d30b9405a72af81bffabd496124a3ed34a77d7223a1ea2712689R8): Imported `useSearchParams` from …
> New URL parameter for the selected network view

- src/components/TableBrowser/TableBrowser.tsx
- src/features/TableDataLoader/components/JoinTableToNetwork/TableColumnAppendForm.tsx
- Manually call 'setNetworkModified' in the various table browser functions instead of listening to all changes in the table.
Should fix CW-542
> Hotfix for issue where the table browser would block the UI

- src/components/FloatingToolBar/ShareNetworkButtton.tsx
- src/components/Workspace/WorkspaceEditor.tsx
This pull request includes changes to improve the behavior of selection state restoration and URL parameter updates in the network-sharing and workspace editor components. The most important changes involve removing unnecessary `setTimeout` calls and adding functionality to restore the active network view after a delay.
This fix will avoid missing selection problem after copy & paste.
* [`src/components/FloatingToolBar/ShareNetworkButtton.tsx`](diffhunk://#diff-d804b4c2f3987fc8d4d3d917df9ee6d15c60109534c67538ea452cc64587af56L89-L91): Removed the `setTimeout` wrapper around the `setSearch` function to simplify the code and ensure immediate updates to URL parameters when no nodes or edges are selected.
* [`src/components/FloatingToolBar/ShareNetworkButtton.tsx`](diffhunk://#diff-d804b4c2f398 …
> Fixed missing selection issue when copy & paste URL

- src/components/ToolBar/EditMenu/DeleteSelectedNodesMenuItem.tsx
- src/components/ToolBar/EditMenu/UndoMenuItem.tsx
- src/task/UndoStack.tsx
This pull request introduces updates to undo functionality for subnetworks. The changes focus on ensuring the correct network context is used when performing actions, and removing unused code.
* Updated `DeleteSelectedNodesMenuItem` to account for the active network view. Added logic to disable the menu item when the active network view differs from the main network or when no nodes are selected. (`src/components/ToolBar/EditMenu/DeleteSelectedNodesMenuItem.tsx`, [[1]](diffhunk://#diff-9d556ccabfe524ff6f3de49cada2ae6cdaaa7f06ae305efe4cb6a6a90181ac4cR34-R42) [[2]](diffhunk://#diff-9d556ccabfe524ff6f3de49cada2ae6cdaaa7f06ae305efe4cb6a6a90181ac4cL42-R60)
* Refactored `useUndoStack` to dynamically determine the target network ID at the moment of execution, addressing potential "stale closure" …
> CW-551 Fix for undo function issues for the subnetworks

- src/components/Vizmapper/index.tsx
- src/models/VisualStyleModel/impl/CustomGraphicsImpl.ts
- src/models/VisualStyleModel/impl/compute-view-util.ts
- Fix issue where the user would not be able to add a custom graphic to nodes if there are no existing custom graphic properties set
- Disable custom graphics sizes for pie charts and render the pie size to be the min of height and width per node
- Dont expose custom graphics size visual properties in the vizmapper
- Add a tooltip communicating to the user the limitations of rendering custom graphics at specific sizes
- All changes described avoid the case of rendering a custom graphic that is larger than the node dimensions leading to rendering issues
> custom graphics bugs

- src/components/Workspace/SidePanel/SidePanel.tsx
- src/components/Workspace/SidePanel/TabPanel.tsx
- src/components/Workspace/WorkspaceEditor.tsx
- src/features/HierarchyViewer/components/MainPanel.tsx
The current version has an empty area when opening sub-networks in the right-panel (see the picture below) on a wide display.
This pull request fix the issue and refactors the layout and styling of components in the workspace, focusing on replacing `Container` with `Box` for layout consistency, improving flexbox usage, and enhancing responsiveness. The changes primarily affect the `SidePanel`, `TabPanel`, `WorkspaceEditor`, and `MainPanel` components.
* Replaced `Container` with `Box` in `SidePanel` for layout consistency and removed the `disableGutters` property. (`src/components/Workspace/SidePanel/SidePanel.tsx`, [[1]](diffhunk://#diff-212cf432544bfdd5efe336045d480102f03e26a28dc98b6434db91fa4bf63c29L1-R1) [[2]](diffhunk://#diff-212cf432544bfdd5efe336045d480102f03e26a28dc98b6434db91fa4bf …
> Reorganized right-panel to correctly expand contents for wide displays

- src/components/SummaryPanel/NdexNetworkPropertyEditor.tsx
- src/components/SummaryPanel/NdexNetworkPropertyTable.tsx
Fixed the issue reported in CW-583. The confirm/cancel button was not visible to users when the description field is long. The new layout limits the height of the description field.
> Adjust the style of network property editor to always show the confirm/cancel button (CW-583)
